import { localized as l } from "@/lib/product-discovery";
// Guides own the how/why/troubleshooting intent; tool pages own the lookup intent.
export const computeGuideCopy = {
  flyai: {
    title: l([
      "fly.ai 算力积分怎么看：地址、月份与份额",
      "fly.ai 算力積分怎麼看：地址、月份與份額",
      "How to read fly.ai compute points: address, month and share",
      "fly.ai 컴퓨팅 포인트 읽기: 주소·월·비율",
      "fly.ai計算ポイントの読み方：アドレス・月・割合",
    ]),
    description: l([
      "用公开收益地址核对月份和积分，区分钱包统计与设备收益。",
      "以公開收益地址核對月份和積分，區分錢包統計與設備收益。",
      "Check monthly points by payout address and distinguish wallet totals from device earnings.",
      "공개 수령 주소로 월별 포인트를 확인하고 지갑 집계와 기기 수익을 구분합니다.",
      "公開受取アドレスで月次ポイントを確認し、ウォレット集計と機器収益を区別します。",
    ]),
    steps: l([
      "从 fly.ai 官方算力页面复制 ETH 公开收益地址。在工具页查询后，核对来源返回的积分月份；本工具不提供历史月份切换。同一地址的多台机器共享钱包统计，不能把同一笔月度积分复制成每台机器的今日收益。",
      "從 fly.ai 官方算力頁面複製 ETH 公開收益地址。在工具頁查詢後核對來源返回的積分月份；本工具不提供歷史月份切換。同地址多台機器共用錢包統計，不能把月度積分複製成每台設備的今日收益。",
      "Copy the public ETH payout address from the official compute page, query it in the tool and check the returned month. The tool has no historical-month selector. Machines sharing an address share the wallet total; do not assign that monthly total to every device as daily income.",
      "공식 컴퓨팅 페이지의 공개 ETH 수령 주소를 복사하고 도구에서 조회하고 반환된 월을 확인합니다. 과거 월 선택은 지원하지 않습니다. 같은 주소의 기기들은 지갑 총계를 공유하므로 월별 총계를 각 기기의 오늘 수익으로 복제하면 안 됩니다.",
      "公式計算ページの公開ETH受取アドレスをコピーし、ツールで照会し、返された月を確認します。過去の月を選ぶ機能はありません。同じアドレスの機器はウォレット集計を共有します。月次合計を各機器の日次収益に割り当てないでください。",
    ]),
    fields: l([
      "积分是来源返回月份的算力记账量；份额是该地址在来源统计中的占比。两者都不是可提现金额。成功读取时间只说明本站何时拿到数据，不是設備心跳。",
      "積分是來源返回月份的算力記帳量；份額是該地址在來源統計中的占比。兩者都不是可提領金額，成功讀取時間也不是設備心跳。",
      "Points describe the source’s returned month; share describes the address’s fraction in that source. Neither is withdrawable cash. Fetch time says when the website read the record, not when a machine last ran.",
      "포인트는 반환된 월의 기록이고 비율은 소스 내 주소의 점유율입니다. 둘 다 출금 가능한 현금이 아닙니다. 조회 시각은 기록을 읽은 시각이며 기기 가동 시각이 아닙니다.",
      "ポイントは返された月の記録、割合は取得元でのアドレスの比率です。出金可能な現金ではありません。取得時刻は記録を読んだ時刻で、機器の稼働時刻ではありません。",
    ]),
    check: l([
      "没有记录时，先检查地址和月份；不要據此判断设备离线。若需要单机排错，回到官方应用。",
      "沒有紀錄時先檢查地址與月份，不要據此判斷設備離線。單機排錯請回官方應用。",
      "If no record appears, check both address and month before judging uptime. Use the official application for machine-level troubleshooting.",
      "기록이 없으면 주소와 월을 먼저 확인하세요. 기기 문제는 공식 앱에서 점검합니다.",
      "記録がなければアドレスと月を先に確認します。実機の調査は公式アプリで行います。",
    ]),
  },
  nosana: {
    title: l([
      "Nosana 节点没有任务怎么办：地址核对与任务字段",
      "Nosana 節點沒有任務怎麼辦：地址核對與任務欄位",
      "Why does my Nosana node have no jobs? Address and job checks",
      "Nosana 노드에 작업이 없는 이유: 주소와 작업 필드 확인",
      "Nosanaノードにジョブがない時：アドレスと項目を確認",
    ]),
    description: l([
      "按节点地址核对 running 与 completed，区分任务空闲、查询失败和节点离线。",
      "依節點地址核對 running 與 completed，區分任務閒置、查詢失敗和節點離線。",
      "Read running and completed by node address without confusing idle jobs, failed queries and offline nodes.",
      "노드 주소별 running·completed를 읽고 작업 없음, 조회 실패, 오프라인을 구분합니다.",
      "ノード別のrunning・completedを確認し、待機・取得失敗・オフラインを区別します。",
    ]),
    steps: l([
      "在官方节点页面确认节点的 Solana 公开地址，不要复制任务地址。将节点地址粘贴到 Nosana 工具页，查询后对照官方同一节点的任务记录；全网统计不能替代节点查询。",
      "在官方節點頁確認 Solana 公開地址，不要複製任務地址。貼至 Nosana 工具頁，與官方同一節點任務紀錄對照；全網統計不能替代節點查詢。",
      "Confirm the node’s public Solana address in the official node page, not a job address. Query it in the tool and compare jobs for the same node. Network-wide totals are not this node’s results.",
      "공식 노드 페이지에서 작업 주소가 아닌 노드의 공개 Solana 주소를 확인합니다. 도구의 결과와 같은 노드의 공식 작업 기록을 비교하세요. 전체 네트워크 집계는 해당 노드의 결과가 아닙니다.",
      "公式ノード画面でジョブではなくノードの公開Solanaアドレスを確認します。同じノードの公式ジョブ記録とツールを照合します。全網合計をそのノードの結果として読まないでください。",
    ]),
    fields: l([
      "running 是索引返回的运行中任务数；completed 是该节点的完成任务计数。任务可能跨越多个 GPU；任务数不能证明 GPU 台数，更不能换算 NOS 收益。",
      "running 是索引返回的執行中任務數；completed 是節點完成任務計數。任務可跨多個 GPU，任務數不能證明 GPU 台數或換算 NOS 收益。",
      "running is the index’s current job count; completed is its completed-job count for the node. Jobs may span GPUs, so neither field is a hardware count or a NOS earnings amount.",
      "running은 인덱스의 실행 작업 수이고 completed는 노드의 완료 작업 수입니다. 작업은 여러 GPU에 걸칠 수 있으므로 GPU 수나 NOS 수익으로 환산하지 않습니다.",
      "runningはインデックスの実行中ジョブ数、completedはノードの完了数です。ジョブは複数GPUを使う場合があります。GPU台数やNOS収益への換算はできません。",
    ]),
    check: l([
      "running 为 0 且查询成功，只说明索引没有运行中的任务；先在官方节点页面检查资格、连接和任务分配。请求失败显示未知，不能按 0 处理。",
      "running 為 0 且查詢成功，只說明索引沒有執行中任務；到官方頁檢查資格、連線和分配。請求失敗是未知，不作 0 處理。",
      "A successful running=0 result means no indexed running jobs. Check eligibility, connection and assignment in the official node page. A failed request is unknown, not zero.",
      "성공한 running=0은 인덱스상 실행 작업이 없다는 뜻입니다. 공식 페이지에서 자격·연결·배정을 확인하세요. 요청 실패는 0이 아니라 알 수 없음입니다.",
      "取得成功でrunning=0なら、索引上の実行ジョブがありません。資格・接続・割り当ては公式画面で確認します。取得失敗はゼロではなく不明です。",
    ]),
  },
  gonka: {
    title: l([
      "Gonka Host 是否参与本轮：地址、模型和权重怎么核对",
      "Gonka Host 是否參與本輪：地址、模型和權重怎麼核對",
      "Is my Gonka Host in this epoch? Check address, models and weight",
      "Gonka Host가 이번 에포크에 있나요? 주소·모델·가중치 확인",
      "Gonka Hostは今期に参加している？アドレス・モデル・重みの確認",
    ]),
    description: l([
      "用真实公开接口与工具截图核对 Host 轮次记录，解释权重为何不是日收益。",
      "以真實公開介面與工具截圖核對 Host 輪次紀錄，說明權重為何不是日收益。",
      "Compare a real public API record with the monitor and learn why epoch weight is not daily income.",
      "실제 공개 API 기록과 모니터 화면을 비교하고 에포크 가중치가 일일 수익이 아닌 이유를 확인합니다.",
      "実際の公開API記録と監視画面を照合し、重みと日次収益の違いを確認します。",
    ]),
    steps: l([
      "在官方 Host 配置中核对 gonka1 开头的账户地址。工具页先读取 current/participants，再以完整 index 精确匹配。不要用 inference_url、validator_key 或某个 ML node 的名称替代 Host 地址。",
      "在官方 Host 設定核對 gonka1 帳戶地址。工具先讀取 current/participants，再精確比對完整 index。不要用 inference_url、validator_key 或 ML node 名稱代替。",
      "Confirm the gonka1 Host account address in your official configuration. The tool reads current/participants and matches the complete index. An inference_url, validator_key or ML node name is not a substitute for the Host address.",
      "공식 설정에서 gonka1 Host 계정 주소를 확인합니다. 도구는 current/participants의 전체 index를 정확히 비교합니다. inference_url, validator_key, ML node 이름은 Host 주소가 아닙니다.",
      "公式設定のgonka1 Hostアドレスを確認します。ツールはcurrent/participantsの完全なindexを照合します。inference_url、validator_key、ML node名はHostアドレスの代わりにはなりません。",
    ]),
    fields: l([
      "epoch_id 标识本次轮次；index 是 Host 公开地址；models 是此记录列出的模型；weight 是本轮权重。ml_nodes 中按 node_id 去重得到逻辑节点数。它们都不直接表示美元、GNK 入账或物理 GPU 台数。",
      "epoch_id 標識輪次；index 是 Host 公開地址；models 為紀錄中的模型；weight 為本輪權重。ml_nodes 依 node_id 去重是邏輯節點數，不能直接表示美元、GNK 入帳或 GPU 台數。",
      "epoch_id identifies the epoch; index is the Host public address; models lists the record’s models; weight is its epoch weight. Deduplicated node_id values in ml_nodes count logical nodes, not physical GPUs. None is a USD or credited-GNK amount.",
      "epoch_id는 에포크, index는 Host 공개 주소, models는 등록 모델, weight는 에포크 가중치입니다. ml_nodes의 고유 node_id는 논리 노드 수이며 물리 GPU 수가 아닙니다. USD나 입금 GNK 금액도 아닙니다.",
      "epoch_idは期、indexはHost公開アドレス、modelsは登録モデル、weightは期の重みです。ml_nodesの重複を除いたnode_idは論理ノード数で、GPU台数ではありません。USDや入金GNKの額でもありません。",
    ]),
    check: l([
      "未列入本轮时，先核对地址，再检查官网该轮记录；这不能证明服务器实时离线。若官方接口读取失败，页面应显示未获取或旧数据。入账问题要查官方账本，不能把 weight 直接乘以代币价格。",
      "未列入本輪時先核對地址及官方輪次紀錄，不能推斷伺服器即時離線。讀取失敗是未取得或舊資料。入帳要查官方帳本，不能將 weight 乘以幣價。",
      "If absent, check the address and the same epoch in the official record; absence is not live-uptime evidence. A failed read is unavailable or stale. Check the official ledger for credited rewards rather than multiplying weight by a token price.",
      "목록에 없으면 주소와 같은 에포크의 공식 기록을 확인하세요. 실시간 오프라인 증거는 아닙니다. 읽기 실패는 미조회 또는 오래된 데이터입니다. 입금은 공식 원장을 확인하며 weight에 토큰 가격을 곱하지 않습니다.",
      "記載がなければアドレスと公式の同じ期を確認します。リアルタイムのオフライン判定にはなりません。取得失敗は不明か古いデータです。入金は公式台帳で確認し、weightにトークン価格を掛けないでください。",
    ]),
  },
  akash: {
    title: l([
      "Akash 提供商怎么查：地址、租约和 GPU 容量的区别",
      "Akash 提供商怎麼查：地址、租約和 GPU 容量的差別",
      "How to check an Akash provider: address, leases and GPU capacity",
      "Akash 공급자 확인: 주소·리스·GPU 용량의 차이",
      "Akashプロバイダーの確認：アドレス・リース・GPU容量の違い",
    ]),
    description: l([
      "按提供商地址核对目录记录，理解租约活动和容量数据为何不能代替收入。",
      "依提供商地址核對目錄，說明租約活動和容量資料不能代替收入。",
      "Match a provider directory record and distinguish lease activity, capacity and income.",
      "공급자 디렉터리 기록을 찾고 리스 활동·용량·수익을 구분합니다.",
      "プロバイダーの登録を照合し、リース活動・容量・収益を区別します。",
    ]),
    steps: l([
      "从 Akash 官方提供商目录复制完整公开地址。在工具页查询同一地址，并回到官方 Console 核对提供商与租约。租用者的钱包、部署编号和提供商地址不是同一种标识。",
      "由 Akash 官方提供商目錄複製完整公開地址，查詢後回 Console 對照提供商與租約。租用者錢包、部署編號和提供商地址並非同一標識。",
      "Copy the complete provider public address from the official directory. Query the same address and compare the provider and leases in Console. Tenant wallets and deployment IDs are different identifiers.",
      "공식 디렉터리의 공급자 공개 주소를 복사합니다. Console에서 같은 공급자와 리스를 비교하세요. 임차인 지갑이나 배포 ID와 공급자 주소는 다릅니다.",
      "公式ディレクトリのプロバイダー公開アドレスをコピーします。Consoleの同じプロバイダーとリースを照合します。借り手のウォレットやデプロイIDとは別の識別子です。",
    ]),
    fields: l([
      "目录状态反映来源记录；租约指标表示服务活动；GPU 容量描述上报资源。容量不能证明实时利用率，租约数量也不能换算成 AKT 或美元收入。",
      "目錄狀態反映來源紀錄；租約指標是服務活動；GPU 容量描述上報資源。容量不證明即時使用率，租約數不能換算 AKT 或美元收入。",
      "Directory status describes the source record, lease indicators describe service activity and GPU capacity describes reported resources. Capacity is not utilization, and a lease count is not an AKT or USD amount.",
      "디렉터리 상태는 소스 기록, 리스는 서비스 활동, GPU 용량은 보고된 자원입니다. 용량은 가동률이 아니며 리스 수를 AKT나 USD로 환산할 수 없습니다.",
      "ディレクトリ状態は取得元の記録、リースはサービス活動、GPU容量は報告リソースです。容量は利用率ではなく、リース数はAKTやUSDの金額ではありません。",
    ]),
    check: l([
      "查不到时确认是提供商地址，检查官方目录是否覆盖该提供商；要查实际结算收入，使用官方租约与付款记录。",
      "查不到時確認提供商地址與官方目錄覆蓋範圍；實際結算收入請查官方租約和付款紀錄。",
      "If missing, confirm the provider address and directory coverage. Use official lease and payment records for settled income.",
      "없으면 공급자 주소와 디렉터리 범위를 확인하세요. 정산 수익은 공식 리스·결제 기록에서 확인합니다.",
      "見つからなければ提供者アドレスとディレクトリ範囲を確認します。確定収益は公式リース・決済記録を参照します。",
    ]),
  },
  ionet: {
    title: l([
      "io.net 设备如何连接监控：设备 ID、读取凭据与奖励",
      "io.net 設備如何連接監控：設備 ID、讀取憑證與獎勵",
      "How to connect an io.net device: ID, read credentials and rewards",
      "io.net 기기 연결: ID·읽기 자격 증명·보상 확인",
      "io.netデバイスの接続：ID・読取認証・報酬の確認",
    ]),
    description: l([
      "解释账户连接步骤、设备信息与区块奖励的范围；真实账户联调仍待验证。",
      "說明帳戶連接、設備資料與區塊獎勵範圍；真實帳戶聯調仍待驗證。",
      "Follow account connection and separate device data from block rewards; real-account validation remains pending.",
      "계정 연결과 기기·블록 보상 데이터를 설명합니다. 실제 계정 검증은 아직 진행되지 않았습니다.",
      "アカウント接続とデバイス・ブロック報酬の範囲を説明します。実アカウント検証は未完了です。",
    ]),
    steps: l([
      "先登录 IOTA Watch，在项目页填写官方控制台的设备 ID，再通过下方连接表单验证并保存平台读取凭据。设备 ID 本身不授予私有数据访问；不要在项目申请表、评论或公开地址输入框提交密钥。",
      "先登入 IOTA Watch，在專案頁填官方控制台的設備 ID，再以下方連接表單驗證並儲存讀取憑證。ID 本身不授予私有資料存取，不要把密鑰貼到申請表或公開地址欄位。",
      "Sign in to IOTA Watch, enter the official device ID on the project page, then validate and save read credentials through its connection form. A device ID alone does not authorize private data. Do not put credentials in requests, comments or public-address fields.",
      "IOTA Watch에 로그인하고 프로젝트 페이지에 공식 기기 ID를 입력한 후 아래 연결 양식에서 읽기 자격 증명을 검증하고 저장하세요. ID만으로 비공개 데이터 권한이 생기지 않습니다. 키를 요청 양식·댓글·공개 주소란에 입력하지 마세요.",
      "IOTA Watchにログインし、プロジェクト画面に公式デバイスIDを入力し、下の接続フォームで読取認証を検証・保存します。IDだけでは非公開データへの権限は得られません。キーを要望欄や公開アドレス欄に入力しないでください。",
    ]),
    fields: l([
      "设备信息描述平台记录的硬件和状态；奖励有自己的区块与周期。状态成功不代表奖励读取也成功。未连接或授权失败时显示未获取；模拟通过不等于已验证真实收益。",
      "設備資料描述平台硬體與狀態，獎勵有各自區塊和期間。狀態成功不代表獎勵也成功。未連接或授權失敗是未取得，模擬通過不代表實際收益已驗證。",
      "Device details describe the platform’s hardware and status; rewards have their own block and period. A successful status read does not prove a reward read succeeded. Missing authorization is unavailable. Mock checks do not verify actual earnings.",
      "기기 정보는 플랫폼의 하드웨어·상태이며 보상은 별도의 블록·기간 데이터입니다. 상태 조회 성공이 보상 조회 성공을 보장하지 않습니다. 미연결·권한 실패는 미조회이며 모의 검증은 실제 수익 검증이 아닙니다.",
      "デバイス情報は登録ハードウェア・状態、報酬は別のブロック・期間のデータです。状態の取得成功は報酬の成功を保証しません。未接続・認証失敗は未取得です。模擬検証で実収益を検証したことにはなりません。",
    ]),
    check: l([
      "若连接失败，到官方账户核对凭据权限与设备归属；不尝试扩大读取权限来掩盖缺失。本站目前缺少真实账户验证样本，不承诺已完成真实收益联调。",
      "連接失敗時到官方帳戶核對權限與設備歸屬。本站沒有真實帳戶驗證樣本，不能宣稱已完成真實收益聯調。",
      "Check credential permissions and device ownership in the official account after a connection failure. There is currently no real-account validation sample for this integration.",
      "연결 실패 시 공식 계정에서 권한과 기기 소유를 확인하세요. 현재 이 연결의 실제 계정 검증 샘플은 없습니다.",
      "接続失敗時は公式アカウントで権限と機器の所有を確認します。この連携には現時点で実アカウントの検証サンプルがありません。",
    ]),
  },
  vast: {
    title: l([
      "Vast.ai Host 收入怎么核对：Machine ID、连接与期间",
      "Vast.ai Host 收入怎麼核對：Machine ID、連接與期間",
      "How to verify Vast.ai host income: Machine ID, connection and period",
      "Vast.ai 호스트 수익 확인: Machine ID·연결·기간",
      "Vast.aiホスト収入の確認：Machine ID・接続・期間",
    ]),
    description: l([
      "区分 Host 机器、出租记录与期间收入，并说明连接要求和实测边界。",
      "區分 Host 機器、出租紀錄與期間收入，說明連接要求和實測範圍。",
      "Separate host machines, rentals and period income, including connection requirements and validation limits.",
      "호스트 기기·대여·기간 수익과 연결 요건 및 검증 범위를 구분합니다.",
      "ホスト機器・貸出記録・期間収入を区別し、接続条件と検証範囲を確認します。",
    ]),
    steps: l([
      "登录后从 Host 机器页面复制 Machine ID，在项目页填写，再通过下方表单验证读取凭据并连接。不要用租客 Instance ID 代替。将查询结果与官方同机器、同期间的出租记录比较。",
      "登入後從 Host 機器頁複製 Machine ID，填至專案頁，再以下方表單驗證讀取憑證，不要用租客 Instance ID。與官方同機器、同期間出租紀錄比較。",
      "Sign in, copy Machine ID from the official Host machines page and enter it in the project page. Validate read credentials in the connection form below. Do not substitute a tenant Instance ID. Compare the same machine and period with official rental records.",
      "로그인 후 공식 Host 기기 페이지의 Machine ID를 입력하고 아래 연결 양식에서 읽기 자격 증명을 검증하세요. 임차인 Instance ID는 다릅니다. 같은 기기·기간의 공식 대여 기록과 비교합니다.",
      "ログインして公式Host machinesのMachine IDを入力し、下の接続フォームで読取認証を検証します。借り手のInstance IDとは別です。同じ機器・期間の公式貸出記録と比較します。",
    ]),
    fields: l([
      "硬件与出租状态属于机器记录；收入必须同时看币种和期间。账户余额、小时报价和已确认出租收入不是同一项指标。缺少某项读取权限时保持未知，不用余额推算今日收入。",
      "硬體和出租狀態屬於機器紀錄；收入必須核對幣種及期間。帳戶餘額、時租報價與確認收入不同，缺權限時保持未知，不用餘額推算今日收入。",
      "Hardware and rental status belong to the machine record. Read currency and period alongside income. Account balance, hourly asking price and confirmed rental income are different metrics; do not infer today’s income from a balance.",
      "하드웨어·대여 상태는 기기 기록입니다. 수익은 통화와 기간을 함께 읽습니다. 계정 잔액·시간당 가격·확정 대여 수익은 다르며 잔액으로 오늘 수익을 추정하지 않습니다.",
      "ハードウェア・貸出状態は機器の記録です。収入には通貨と期間が必要です。残高・時間単価・確定貸出収入は別の指標で、残高から今日の収入を推測しません。",
    ]),
    check: l([
      "真实 Host 账户联调尚未完成；目前验证的是模拟响应与异常处理。发现数据差异时保留官方期间和金额截图，先比较范围，再检查连接权限。",
      "真實 Host 帳戶聯調未完成，目前只驗證模擬回應與異常處理。差異請保留官方期間和金額截圖，先比對範圍再查權限。",
      "Real Host account validation is pending; current checks cover mocked responses and failure handling. When figures differ, retain the official period and amount, compare scope and then check permissions.",
      "실제 Host 계정 검증은 대기 중이며 현재는 모의 응답과 오류 처리 검증입니다. 차이가 나면 공식 기간·금액을 기록하고 범위를 비교한 뒤 권한을 확인하세요.",
      "実Hostアカウントの検証は未完了です。現在は模擬応答と異常処理を検証しています。差があれば公式の期間・金額を残し、範囲と権限を確認します。",
    ]),
  },
  golem: {
    title: l([
      "Golem 收益为什么对不上：节点地址与近 24 小时口径",
      "Golem 收益為什麼對不上：節點地址與近 24 小時口徑",
      "Why do Golem earnings differ? Node address and last-24-hour scope",
      "Golem 수익이 다른 이유: 노드 주소와 최근 24시간 기준",
      "Golem収益が合わない時：ノードアドレスと直近24時間",
    ]),
    description: l([
      "核对节点统计中的 GLM 与滚动 24 小时，避免与香港自然日或钱包余额混算。",
      "核對節點 GLM 與滾動 24 小時，避免與香港自然日或錢包餘額混算。",
      "Check node GLM earnings over a rolling 24 hours rather than mixing them with a Hong Kong day or wallet balance.",
      "노드 GLM 수익의 최근 24시간을 홍콩 달력 일자나 지갑 잔액과 구분합니다.",
      "ノードのGLM収益の直近24時間を香港の暦日やウォレット残高と区別します。",
    ]),
    steps: l([
      "从 Golem 官方节点统计确认 Node ID 的公开地址，再到工具页查询。不要只凭地址外观认定收款钱包就是节点。比较数据时，使用同一 Node ID 与相同读取时刻附近的记录。",
      "由 Golem 官方節點統計確認 Node ID 公開地址，再到工具查詢。不要憑外觀認定收款錢包就是節點。對照同一 ID 及相近讀取時刻。",
      "Confirm the public Node ID in official statistics, then query it in the tool. An address looking like a wallet does not establish node identity. Compare the same ID and records fetched around the same time.",
      "공식 통계에서 공개 Node ID를 확인하고 조회하세요. 지갑처럼 보이는 주소만으로 노드 ID라고 판단하지 않습니다. 같은 ID와 비슷한 조회 시각을 비교하세요.",
      "公式統計で公開Node IDを確認してから照会します。アドレスの見た目だけでウォレットとノードを同一視しません。同じIDと近い取得時刻で比較します。",
    ]),
    fields: l([
      "近 24 小时是来源定义的滚动窗口，币种是 GLM。它不等于香港时间今日 00:00 起的 IOTA 记账。钱包转账或余额也不是这一窗口的计算收益。",
      "近 24 小時是來源定義的滾動期間，單位 GLM；不是香港今日 00:00 起的 IOTA 記帳。錢包轉帳或餘額也不是此期間計算收益。",
      "The source defines a rolling last-24-hour GLM window. It is different from IOTA’s Hong Kong-midnight accounting day. Wallet transfers and balances are not that window’s compute earnings.",
      "소스는 최근 24시간의 GLM 이동 구간을 사용합니다. 홍콩 자정부터의 IOTA 기록과 다릅니다. 지갑 송금·잔액도 그 기간의 계산 수익이 아닙니다.",
      "取得元はGLMの直近24時間という移動期間を使います。香港午前0時からのIOTA記帳とは異なります。ウォレットの送金や残高もこの期間の計算収益ではありません。",
    ]),
    check: l([
      "若金额不同，先比较期间和刷新时刻，再检查是否使用了正确 Node ID。缺记录显示未知；不能把 GLM 原币数量直接加到 IOTA 今日原币收益中。",
      "金額不同先比對期間與刷新時刻，再核對 Node ID。缺紀錄是未知，不能將 GLM 數量直接加至 IOTA 今日原幣收益。",
      "Compare period and fetch time before investigating the Node ID. Missing records are unknown. GLM token amounts cannot be added directly to IOTA token amounts.",
      "금액이 다르면 기간·조회 시각을 먼저 비교한 후 Node ID를 확인하세요. 기록 없음은 알 수 없음이며 GLM 수량을 IOTA 수량에 직접 더하지 않습니다.",
      "金額が違えば期間と取得時刻を先に比較し、Node IDを確認します。記録なしは不明です。GLM数量をIOTA数量に直接加算できません。",
    ]),
  },
} as const;
export const guideSections = {
  input: l([
    "怎样找到并查询正确标识？",
    "如何找到並查詢正確標識？",
    "Find and query the correct identifier",
    "올바른 식별자로 조회하기",
    "正しいIDで照会する",
  ]),
  fields: l([
    "结果字段怎么读？",
    "結果欄位怎麼讀？",
    "Read the result fields",
    "결과 필드 읽기",
    "結果項目を読む",
  ]),
  check: l([
    "查不到或对不上，先检查什么？",
    "查不到或不一致，先檢查什麼？",
    "Check missing or mismatched results",
    "누락·불일치 확인하기",
    "未取得・不一致を確認する",
  ]),
};
