import { withLocales } from "@/components/site/localization";
import type { Article } from "./articles";

const sources = [
  { name: "Macrocosmos · Train at Home", url: "https://iota.macrocosmos.ai/" },
  {
    name: "Macrocosmos · TAH user guide",
    url: "https://docs.macrocosmos.ai/product-and-services/tah/tah-user-guide",
  },
  { name: "IOTA Watch · source code", url: "https://github.com/molimao/iota" },
];

export const dataGuides: Article[] = withLocales([
  {
    slug: "data-sources-and-freshness",
    published: "2026-10-01",
    modified: "2026-10-01",
    sources,
    topic: { en: "Data reliability", zh: "数据可靠性" },
    title: {
      en: "Where IOTA Watch data comes from and how often it refreshes",
      zh: "IOTA Watch 数据来自哪里，多久更新一次？",
    },
    description: {
      en: "Official API sources, refresh intervals, sample timestamps and stale data: how to tell whether an IOTA Train at Home reading is current.",
      zh: "了解 IOTA Train at Home 官网 API 数据来源、刷新周期、采样时间与旧数据标记，判断设备状态和收益是否及时。",
    },
    body: {
      en: [
        "IOTA Watch reads the public Macrocosmos mainnet API. Device status, rewards and training statistics have separate update clocks; refreshing one does not make the others current.",
        "## Which sources feed each view?",
        "- Device discovery: active runs and the miner roster for every active run",
        "- Network view: runs, run occupancy, miner rosters and run progress",
        "- Rewards: entitlement totals and reward history, fetched independently",
        "- Training history: metrics, throughput and cumulative tokens for the selected run and period",
        "The API base is [iota-web.api.macrocosmos.ai/mainnet](https://iota-web.api.macrocosmos.ai/mainnet/runs). These are public readings; IOTA Watch cannot read local device logs or control the official training app.",
        "## How often does the page update?",
        "While the page is visible, device status normally checks every 30 seconds and rewards every two minutes. Network miner rosters and progress check about once a minute. Server caches last 60 seconds for miner rosters and progress, 120 seconds for occupancy, and five minutes for runs, rewards and historical metrics. Repeated page checks may reuse a valid cached response.",
        "Manual refresh has a 15-second cooldown. It can request newer data, but still respects official rate limits and retry delays. Background polling pauses while the page is hidden.",
        "## Fetch time versus sample time",
        "Fetch time records the last successful read of that source. Sample time is when the official API recorded a training statistic. A successful read can contain an old sample; that alone does not show a machine is offline.",
        "## What happens when a source fails?",
        "Previous successful values remain visible with a warning and their original fetch time. Missing data stays unknown. Reward totals and reward history can fail separately, so one usable field does not imply that every reward field is current.",
        "A device refresh interrupted for more than five minutes is a data-read warning. See [refresh interrupted](/learn/what-refresh-interrupted-means). A [partial network view](/learn/network-status-explained) reports the number of rosters successfully read.",
      ],
      zh: [
        "IOTA Watch 读取 Macrocosmos 的公开主网 API。设备状态、收益与训练统计分别记录更新时间；某一项刷新成功，不会让其他项目自动变成最新。",
        "## 各页面使用哪些数据源？",
        "- 设备查找：进行中的任务，以及每个任务的矿工名单",
        "- 全网现况：任务列表、网络名额、矿工名单和任务进度",
        "- 收益：分别读取记账总额与收益历史记录",
        "- 训练历史：所选任务与时间范围内的训练指标、吞吐量和累计 token 数",
        "API 基础地址是 [iota-web.api.macrocosmos.ai/mainnet](https://iota-web.api.macrocosmos.ai/mainnet/runs)。这些是公开上报数据，本站无法读取设备本地日志或控制官方训练应用。",
        "## 页面多久更新一次？",
        "页面可见时，设备状态通常每 30 秒检查一次，收益每 2 分钟检查一次；全网矿工名单与进度约每分钟检查一次。服务端对矿工名单与进度缓存 60 秒，网络名额缓存 120 秒，任务列表、收益和历史指标缓存 5 分钟。多次检查可能复用仍有效的缓存结果。",
        "手动刷新有 15 秒冷却，可请求较新的数据，但仍遵守官方限流和重试等待。页面隐藏时暂停后台轮询。",
        "## 拉取时间与采样时间有什么区别？",
        "拉取时间是该数据源最近一次成功读取的时间；采样时间是官方记录训练统计的时间。成功读取也可能返回较旧的采样，不能仅据此判断机器离线。",
        "## 接口失败后会发生什么？",
        "上次成功的数据会保留，并显示警告和原来的拉取时间。缺失数据仍为未知。收益总额与收益记录可能分别失败，因此一个字段可用，不代表所有收益数据都是最新。",
        "设备数据超过 5 分钟没能成功更新，会提示读取中断。详见 [刷新中断说明](/learn/what-refresh-interrupted-means)。[全网数据不完整](/learn/network-status-explained) 时会注明成功读取了多少份名单。",
      ],
    },
  },
  {
    slug: "training-history-and-metrics",
    published: "2026-10-01",
    modified: "2026-10-01",
    sources,
    topic: { en: "Training history", zh: "训练历史" },
    title: {
      en: "How to read IOTA Train at Home training history and throughput",
      zh: "IOTA Train at Home 训练历史、吞吐量与贡献率怎么看？",
    },
    description: {
      en: "Read daily, weekly and monthly training trends, epoch tokens, throughput, contribution percentage and rank without confusing them with rewards.",
      zh: "按日、周、月查看训练趋势，理解 epoch token 数、吞吐量、贡献率和排名，区分训练指标与记账收益。",
    },
    body: {
      en: [
        "Open a saved device’s details, select a training run, then choose day, week or month. The chart and table show official historical samples for that selection. Training volume is not a token payout or a reward forecast.",
        "## Which metrics can I compare?",
        "- Tokens: reported training token count for an epoch",
        "- Throughput: processing rate reported by the official history API",
        "- Cumulative tokens: the cumulative training token count, separate from lifetime rewards",
        "- Contribution: the reported fraction displayed as a percentage; 0.02 displays as 2%",
        "- Rank and participants: the reported position and participant count for that epoch, when available",
        "Switch the chart between tokens, throughput and cumulative tokens. The table preserves the individual samples so the trend can be checked against the numbers.",
        "## Why can the chart have gaps?",
        "The three history sources may contain different epochs. IOTA Watch joins values by epoch instead of assuming the array positions line up. A missing measurement is a gap, not an invented zero.",
        "## Why is the selected run empty?",
        "The official API may have no samples for this Miner ID in the chosen run or period. Check the task selection, try another period and inspect source warnings. An empty history does not prove that the device has failed.",
        "For current activity, read [device status](/learn/device-status). For accounted tokens, read [how rewards work](/learn/how-rewards-work). [Data freshness](/learn/data-sources-and-freshness) explains why recent retrieval can still contain older samples.",
      ],
      zh: [
        "打开已保存设备的详情，选择训练任务，再切换日、周或月。趋势图和表格展示所选范围内的官方历史采样。训练量不是代币到账金额，也不是未来收益预测。",
        "## 可以对比哪些指标？",
        "- Tokens：某个 epoch 上报的训练 token 数",
        "- 吞吐量：官方历史接口上报的处理速率",
        "- 累计 tokens：累计训练 token 数，与累计收益分开计算",
        "- 贡献率：把上报的比例显示为百分比，例如 0.02 显示为 2%",
        "- 排名与参与人数：该 epoch 上报的名次及参与人数，有数据时才展示",
        "趋势图可切换训练量、吞吐量或累计训练量。下方表格保留每次采样，便于对照图形与具体数字。",
        "## 为什么曲线会有空缺？",
        "三个历史数据源可能包含不同的 epoch。本站按 epoch 对齐数据，不假定数组中的相同位置属于同一次训练。缺失的测量值保留为空缺，不补成 0。",
        "## 为什么所选任务没有历史？",
        "官方 API 可能尚未提供该 Miner ID 在所选任务或时间范围内的采样。请核对任务选择，切换时间范围，并查看数据源警告。历史为空不能直接证明设备故障。",
        "当前活动看 [设备状态](/learn/device-status)，记账代币看 [收益口径](/learn/how-rewards-work)。[数据时效说明](/learn/data-sources-and-freshness) 解释了为什么刚拉取的数据仍可能包含旧采样。",
      ],
    },
  },
  {
    slug: "network-status-explained",
    published: "2026-10-01",
    modified: "2026-10-03",
    sources,
    topic: { en: "Network status", zh: "全网现况" },
    title: {
      en: "IOTA Train at Home network status: slots, roster miners and training progress",
      zh: "IOTA Train at Home 全网状态：名额、名单矿工与训练进度",
    },
    description: {
      en: "Understand active runs, roster coverage, online versus training miners and partial network data before diagnosing an individual device.",
      zh: "理解进行中的任务、名单覆盖率、在线与训练人数的区别，以及全网数据不完整时该如何判断。",
    },
    body: {
      en: [
        "The [network page](/network) shows public IOTA Train at Home runs without requiring a Miner ID or sign-in. It gives context for your device: which runs exist, their available slots and the activity reported by the network.",
        "## Roster miners are different from training miners",
        "Roster miners count unique public Miner IDs across fetched runs. Training counts IDs with throughput above zero in any fetched run, regardless of is_active. The official active flag can be false while throughput is positive. Neither number proves live connectivity or counts IOTA Watch users. Run and tier rows count records within those runs.",
        "## How should I read slots and progress?",
        "Slots come from official run occupancy. Progress and loss describe the whole run, not one device. Available capacity does not guarantee assignment, and the monitoring site cannot allocate a slot.",
        "## What does roster coverage mean?",
        "Coverage compares successfully refreshed miner lists with the runs being checked. For example, 7/8 means one list could not be refreshed. The totals may be incomplete; a failed list is not counted as zero miners. Global miner totals deduplicate public hotkeys across retrieved runs.",
        "Each source has its own retrieval time. Inspect [source freshness](/learn/data-sources-and-freshness) before comparing snapshots. Older successful values are retained with warnings when an update fails.",
        "## Where should I check my own machine?",
        "Add its public Miner ID on [My devices](/app). For missing devices, follow [device not found](/learn/device-not-found). Open the official app for local errors; the network page cannot inspect your Mac.",
      ],
      zh: [
        "[全网页面](/network) 无需 Miner ID 或登录，即可查看 IOTA Train at Home 的公开任务。它提供设备状态的背景：有哪些任务、还剩多少名额，以及网络上报的活动情况。",
        "## 名单矿工与训练人数有什么区别？",
        "名单矿工按已读取任务中的公开 Miner ID 去重；训练人数统计任一已读取任务中吞吐量大于零的 ID，不依赖 is_active。官方 active 标记可能为 false，但仍上报正吞吐量。这两个数字都不是实时在线证明，也不是 IOTA Watch 用户人数。任务表与档位按相应任务的名单记录计数。",
        "## 名额和进度应怎样理解？",
        "名额来自官方任务占用数据。进度与损失描述整个任务，不是单台设备。存在空位不保证立即分配任务，本站也无法分配名额。",
        "## 名单覆盖率是什么意思？",
        "覆盖率比较成功刷新的矿工名单数与正在检查的任务数。例如 7/8 表示一份名单没能更新，总量可能不完整；不会把失败的名单当成 0 个矿工。全网矿工总量会对已获取任务里的公开 hotkey 去重。",
        "各来源分别记录拉取时间。对照数据前，请先检查 [数据时效](/learn/data-sources-and-freshness)。刷新失败时，较旧的成功数据会保留并附上警告。",
        "## 怎样检查自己的机器？",
        "在 [我的设备](/app) 添加公开 Miner ID。设备缺失时，按 [尚未找到设备的排查步骤](/learn/device-not-found) 检查。本地错误请打开官方应用，全网页面无法读取 Mac 的本地状态。",
      ],
    },
  },
]);
