import type { Article } from "./articles";
import {
  problemLinks,
  localized,
  DISCOVERY_UPDATED,
  productQuestions,
} from "@/lib/product-discovery";
import { LOCALES } from "@/lib/site";
const bodies = [
  localized([
    [
      "## 添加设备前，需要哪些信息？",
      "在每台 Mac 的 IOTA Train at Home 应用中复制公开 Miner ID，也就是设备 hotkey。为不同机器填写容易识别的名称。同一个收款 coldkey 可能对应多台设备，监控清单应保留各自的 Miner ID。",
      "## 怎样集中查看并保存清单？",
      "打开 [IOTA 监控](/app)，逐台添加 Miner ID。未登录清单保存在当前浏览器；需要换电脑或手机查看时，使用同一个 Google 账号登录同步。清理浏览器前可导出 JSON 备份。",
      "## 状态和收益应该怎样一起看？",
      "先看最近成功读取时间，再查看上报状态与记账收益。IOTA 今日收益从香港时间 00:00 起统计 pending、settled 记录，美元属于市场估值。状态刷新和收益刷新有各自的时间，不能只凭一个旧采样判断机器已经离线。",
      "## 什么时候回到设备本机？",
      "需要确认应用是否启动、检查网络连接或查看本地日志时，打开对应 Mac 上的官方应用。网页监控不直接读取本机日志或控制训练。遇到异常可继续读 [数据来源与时效](/learn/data-sources-and-freshness)。",
    ],
    [
      "## 新增設備前，需要哪些資訊？",
      "在每台 Mac 的 IOTA Train at Home 應用中複製公開 Miner ID，也就是設備 hotkey，並填寫容易辨識的名稱。同一個收款 coldkey 可能對應多台設備，應保留各自的 Miner ID。",
      "## 如何集中查看並儲存清單？",
      "開啟 [IOTA 監控](/app)，逐台新增 Miner ID。未登入清單儲存在目前瀏覽器；換電腦或手機時可用相同 Google 帳號同步。清除瀏覽器前可匯出 JSON 備份。",
      "## 狀態與收益應如何一起看？",
      "先看最近成功讀取時間，再核對回報狀態與記帳收益。IOTA 今日收益從香港時間 00:00 起統計 pending、settled 紀錄，美元屬於市場估值。兩種資料有不同更新時間，不能只憑舊採樣判斷機器離線。",
      "## 何時回到設備本機？",
      "確認應用是否啟動、網路連接或本機日誌時，開啟對應 Mac 的官方應用。網頁不能直接讀取本機日誌或控制訓練。可繼續閱讀 [資料來源與時效](/learn/data-sources-and-freshness)。",
    ],
    [
      "## What do I need from each Mac?",
      "Copy the public Miner ID, or device hotkey, from IOTA Train at Home on each Mac. Give each machine a recognizable name. Several machines can share a payout coldkey, so keep their separate Miner IDs in the monitoring list.",
      "## How do I keep the list in one place?",
      "Open [IOTA monitoring](/app) and add each Miner ID. A signed-out list stays in the current browser. Use the same Google account to sync it across computers and phones, and export a JSON backup before clearing browser data.",
      "## How should I read activity and rewards together?",
      "Check the last successful fetch time before reading reported activity and accounted rewards. IOTA's day begins at 00:00 Hong Kong time and includes pending and settled records. USD is a market estimate. Activity and reward sources have separate clocks; an old sample alone does not establish that a machine is offline.",
      "## When should I check the Mac itself?",
      "Use the official app on that machine to confirm startup, connectivity or runtime logs. The browser monitor does not read local logs or control training. See [data sources and freshness](/learn/data-sources-and-freshness) for interpreting missing or old results.",
    ],
    [
      "## 각 Mac에서 어떤 정보가 필요한가요?",
      "각 Mac의 IOTA Train at Home에서 공개 Miner ID, 즉 기기 hotkey를 복사하고 구별하기 쉬운 이름을 정하세요. 여러 기기가 같은 수령 coldkey를 사용할 수 있으므로 각 Miner ID를 별도로 보관합니다.",
      "## 목록을 한곳에 보관하려면 어떻게 하나요?",
      "[IOTA 모니터링](/app)에서 각 Miner ID를 추가하세요. 비로그인 목록은 현재 브라우저에 저장됩니다. 같은 Google 계정으로 컴퓨터와 휴대폰에서 동기화하고 브라우저 데이터를 지우기 전에 JSON으로 내보내세요.",
      "## 상태와 보상을 함께 읽는 방법은 무엇인가요?",
      "최근 성공한 조회 시간을 먼저 확인하세요. IOTA 일일 보상은 홍콩 시간 00:00 이후 pending·settled 기록을 계산하며 USD는 시장 추정치입니다. 상태와 보상의 갱신 시각은 서로 다르므로 이전 표본 하나만으로 오프라인을 판단할 수 없습니다.",
      "## 언제 Mac에서 직접 확인해야 하나요?",
      "앱 실행 여부, 연결과 로컬 로그는 해당 Mac의 공식 앱에서 확인하세요. 웹 모니터는 로컬 로그를 읽거나 학습을 제어하지 않습니다. [데이터 출처와 갱신 시각](/learn/data-sources-and-freshness)도 참고할 수 있습니다.",
    ],
    [
      "## 各Macから何を取得しますか？",
      "各MacのIOTA Train at Homeから公開Miner ID、つまりデバイスhotkeyをコピーし、判別しやすい名前を付けます。複数機器が同じ受取coldkeyを使うこともあるため、Miner IDは個別に保存します。",
      "## 一覧をまとめて保存するには？",
      "[IOTA監視](/app)で各Miner IDを追加します。未ログイン時の一覧は現在のブラウザに保存されます。同じGoogleアカウントでPCやスマートフォンに同期し、ブラウザデータを削除する前にJSONをエクスポートできます。",
      "## 状態と報酬をどう照合しますか？",
      "最終取得時刻を先に確認します。IOTAの日次報酬は香港時間00:00以降のpending・settled記録を集計し、USDは市場価格による推計です。状態と報酬の更新時刻は別々なので、古いサンプルだけでオフラインとは判断できません。",
      "## いつ実機で確認しますか？",
      "起動状態、接続、動作ログは該当Macの公式アプリで確認します。ブラウザからローカルログを読んだり学習を制御したりすることはできません。[データの出典と取得時刻](/learn/data-sources-and-freshness)も参照できます。",
    ],
  ]),
  localized([
    [
      "## 一台机器怎样建立一张卡片？",
      "在 [设备总览](/devices) 新建设备，填写名称，再添加这台机器实际使用的各项目标识。已有分散卡片时，可编辑并整理关联；不要仅凭相同用户名判断它们属于同一台物理设备。",
      "## 每个项目需要填什么？",
      "IOTA 使用设备 Miner ID；XID / MMM 使用公开收益地址，定位单台机器时再指定 Worker；fly.ai 使用公开 ETH 收益地址。其他项目的标识类型和授权要求，可在 [项目列表](/projects) 打开对应监控核对。",
      "## 为什么余额、积分没有进入今日收益？",
      "XID 钱包余额与 fly.ai 本月积分不是单台设备当天的记账收益。它们可以在卡片中单独显示，但不会加入设备今日美元合计。某个项目只能提供任务数量或网络权重时，也不会被换算成收益。",
      "## 需要换个项目单独查看时怎么做？",
      "从卡片展开对应项目，打开项目监控查看来源和详情。设备视角帮助整理同一台机器，项目视角用于阅读该项目自己的指标，两者使用同一份关联清单。",
    ],
    [
      "## 一台機器如何建立一張卡片？",
      "在 [設備總覽](/devices) 新增設備，填寫名稱，再加入這台機器實際使用的專案識別碼。已有分散卡片可編輯並整理關聯；不要僅憑相同使用者名稱認定是同一台實體設備。",
      "## 每個專案要填寫什麼？",
      "IOTA 使用設備 Miner ID；XID / MMM 使用公開收益地址，定位單機時再指定 Worker；fly.ai 使用公開 ETH 收益地址。其他專案的識別碼與授權要求，可在 [專案清單](/projects) 開啟對應監控核對。",
      "## 為何餘額與積分沒有計入今日收益？",
      "XID 錢包餘額及 fly.ai 本月積分不是單台設備當天的記帳收益，會獨立顯示，不計入今日美元合計。任務數量和網路權重也不會換算成收益。",
      "## 要單獨查看一個專案時怎麼辦？",
      "在卡片展開專案，再開啟專案監控查看來源與明細。設備視角整理同一台機器，專案視角閱讀該專案指標，兩者使用相同的關聯清單。",
    ],
    [
      "## How do I create one card for a machine?",
      "Create a device in [Devices](/devices), name it, then add identifiers from projects running on that machine. Existing cards can be edited and their bindings organized. A shared username alone does not prove that two identifiers belong to the same physical device.",
      "## What identifier does each project need?",
      "IOTA uses a device Miner ID. XID / MMM uses a public reward address and an explicit Worker when identifying a machine. fly.ai uses a public ETH reward address. Check other identifier types and authorization requirements in the [project list](/projects).",
      "## Why aren't balances and points part of today's earnings?",
      "XID wallet balance and fly.ai monthly points are not a machine's daily accounted earnings. They remain visible as separate metrics and do not enter the device's USD daily total. Task counts and network weights are not converted into revenue either.",
      "## How do I inspect one project separately?",
      "Expand that project on the card and open its monitor for sources and detail. The device view organizes a machine; the project view explains that project's own metrics. Both use the same list of bindings.",
    ],
    [
      "## 기기 한 대를 카드 하나로 만들려면 어떻게 하나요?",
      "[기기 목록](/devices)에 기기를 만들고 이름을 지정한 뒤 해당 기기에서 실행하는 프로젝트 식별자를 추가하세요. 기존 카드의 연결도 편집할 수 있습니다. 사용자 이름이 같다는 이유만으로 같은 물리 기기라고 판단하지 마세요.",
      "## 프로젝트별로 어떤 식별자가 필요한가요?",
      "IOTA는 기기 Miner ID, XID / MMM은 공개 보상 주소와 단일 기기 조회용 Worker, fly.ai는 공개 ETH 보상 주소를 사용합니다. 다른 프로젝트의 식별자와 인증 요구 사항은 [프로젝트 목록](/projects)에서 확인하세요.",
      "## 잔액과 포인트가 오늘 수익에 포함되지 않는 이유는 무엇인가요?",
      "XID 지갑 잔액과 fly.ai 월간 포인트는 기기 일일 정산 수익이 아닙니다. 별도 지표로 표시하며 기기의 USD 일일 합계에 넣지 않습니다. 작업 수나 네트워크 가중치도 수익으로 환산하지 않습니다.",
      "## 프로젝트 하나만 자세히 보려면 어떻게 하나요?",
      "카드에서 프로젝트를 펼치고 해당 모니터를 열어 출처와 상세 정보를 확인하세요. 기기별 화면은 기기를 정리하고 프로젝트별 화면은 고유 지표를 보여주며 연결 목록은 공유합니다.",
    ],
    [
      "## 1台を1枚のカードにまとめるには？",
      "[デバイス一覧](/devices)で機器を作成し、名前と実際に使っているプロジェクトのIDを追加します。既存カードの紐付けも編集できます。同じユーザー名だけで同一の実機と判断しないでください。",
      "## プロジェクトごとに何を入力しますか？",
      "IOTAはデバイスMiner ID、XID / MMMは公開報酬アドレスと単機確認用Worker、fly.aiは公開ETH報酬アドレスを使います。他のID形式と認証要件は[プロジェクト一覧](/projects)で確認できます。",
      "## 残高とポイントが本日の収益に含まれないのはなぜ？",
      "XIDの残高とfly.aiの月間ポイントは実機の日次記帳収益ではありません。別々の指標として表示し、日次USD合計には入れません。ジョブ数やネットワーク重みも収益に換算しません。",
      "## 1つのプロジェクトを詳しく見るには？",
      "カードでプロジェクトを展開し、監視画面で出典と詳細を確認します。デバイス別は機器の整理、プロジェクト別は固有の指標を確認する表示で、同じ紐付け一覧を使います。",
    ],
  ]),
  localized([
    [
      "## 先确定你要完成哪种操作",
      "需要保存多台设备标识、在一处检查状态和收益时，可以先试用 IOTA Watch。要安装、启动任务、修改矿工配置或领取收益时，打开对应官方应用和用户指南。",
      "## 什么情况下集中监控更方便？",
      "经常切换多台 Mac、多个项目或不同公开标识时，可以为设备命名并关联项目，减少重复输入。先核对数据覆盖范围，再判断卡片中的记录是否对应你要查看的机器或钱包。",
      "## 什么情况下必须回到官方来源？",
      "官方规则、运行日志、账号授权、提款和奖励领取应以原项目为准。IOTA Watch 会注明 API 来源及读取时间，但它不证明任务已经在本机正常运行，也不控制平台账号。",
      "## 如何判断这个工具是否适合你？",
      "用一个公开标识检查是否能返回你需要的指标，再添加更多记录。每个项目免费支持 5 台；Pro 提升各项目设备名额到 50 台。需要自己的服务环境时，可查看 [开源仓库与部署指南](https://github.com/molimao/iota)。",
    ],
    [
      "## 先確認你要完成哪一種操作",
      "需保存多台設備識別碼、集中檢查狀態與收益時，可先試用 IOTA Watch。安裝、啟動任務、修改礦工設定或領取收益時，請開啟官方應用與使用指南。",
      "## 何時集中監控更方便？",
      "經常切換多台 Mac、多個專案或不同識別碼時，可為設備命名並關聯專案，減少重複輸入。先核對資料範圍，再確認紀錄對應的是機器還是錢包。",
      "## 何時必須回到官方來源？",
      "官方規則、執行日誌、帳戶授權、提款與獎勵領取以原專案為準。本站標明 API 來源與取得時間，但不能證明任務在本機正常執行，也不控制平台帳戶。",
      "## 如何判斷是否適合你？",
      "先用一個公開識別碼確認所需指標可查，再加入更多紀錄。每個專案免費 5 台，Pro 提升至 50 台。自行部署可查看 [開源倉庫與部署指南](https://github.com/molimao/iota)。",
    ],
    [
      "## Start with the action you need",
      "Try IOTA Watch when you want to save several identifiers and check activity and rewards together. Open the official app and guide when you need installation, job startup, miner configuration or claiming rewards.",
      "## When is a combined monitor useful?",
      "If you regularly switch among Macs, projects or public identifiers, named device cards and project bindings can reduce repeated lookups. Check coverage first and confirm whether a record represents a machine or a wallet.",
      "## When should I use the original source?",
      "Use the project itself for official rules, runtime logs, authorization, withdrawals and reward claims. IOTA Watch names its API sources and fetch times, but a web record does not prove that a job is running correctly on your machine, and the site does not control platform accounts.",
      "## How can I evaluate whether it fits?",
      "Look up one public identifier to check the metrics you need before adding more records. Free supports 5 devices per project; Pro raises each project's limit to 50. For a self-hosted environment, see the [source repository and deployment guide](https://github.com/molimao/iota).",
    ],
    [
      "## 필요한 작업부터 정하세요",
      "여러 식별자를 저장하고 상태·보상을 모아 확인하려면 IOTA Watch를 먼저 사용해 보세요. 설치, 작업 시작, 채굴 설정 또는 보상 수령은 공식 앱과 안내를 이용합니다.",
      "## 통합 모니터가 편리한 경우는 언제인가요?",
      "여러 Mac, 프로젝트와 공개 식별자를 자주 바꿔 확인한다면 이름 있는 카드와 프로젝트 연결로 반복 입력을 줄일 수 있습니다. 먼저 데이터 범위를 확인하고 해당 기록이 기기인지 지갑인지 구별하세요.",
      "## 원래 출처를 사용해야 하는 경우는 언제인가요?",
      "공식 규칙, 실행 로그, 인증, 출금과 보상 수령은 해당 프로젝트를 이용하세요. IOTA Watch는 출처와 조회 시각을 표시하지만 작업이 기기에서 정상 실행된다는 증거가 아니며 플랫폼 계정을 제어하지 않습니다.",
      "## 내 용도에 적합한지 어떻게 판단하나요?",
      "공개 식별자 하나로 필요한 지표가 나오는지 확인한 뒤 더 추가하세요. 프로젝트당 무료 5대, Pro 50대입니다. 직접 호스팅하려면 [소스 코드와 배포 안내](https://github.com/molimao/iota)를 참고하세요.",
    ],
    [
      "## まず必要な操作を決めます",
      "複数のIDを保存して状態と報酬をまとめて確認したい場合はIOTA Watchを試せます。導入、ジョブの開始、マイナー設定、報酬受領には公式アプリと案内を使います。",
      "## 集約した監視が便利な場面は？",
      "Mac、プロジェクト、公開IDを頻繁に切り替えて確認する場合、名前付きカードと紐付けで再入力を減らせます。データ範囲を確認し、記録が実機かウォレットかを区別してください。",
      "## 元の出典を使うべき場面は？",
      "公式ルール、動作ログ、認証、出金、報酬受領は該当プロジェクトで行います。本站は出典と取得時刻を示しますが、実機での正常動作を証明したり公式アカウントを制御したりはしません。",
      "## 自分の用途に合うか確認するには？",
      "公開IDを1つ照会し、必要な指標があるか確認してから追加します。無料は各プロジェクト5台、Proは50台です。自分でホストする場合は[ソースコードと配置案内](https://github.com/molimao/iota)を参照できます。",
    ],
  ]),
  localized([
    [
      "## 合计前，先核对三个条件",
      "同一币种、同一统计周期、同一数据归属，才有比较或合计的基础。余额是某一时点的存量，今日收益是某个周期的增量；积分、任务数量与网络权重也不能直接当作现金收入。",
      "## 今日、UTC 日和近 24 小时有什么区别？",
      "IOTA 与 Vast.ai 的今日统计使用香港时间日界；io.net 区块奖励使用 UTC 日；Golem 近 24 小时是滚动窗口。跨午夜或比较两台机器时，先看各条记录的周期标签。fly.ai 月度积分应按对应月份阅读。",
      "## 美元估值和缺失价格怎样处理？",
      "IOTA 的美元金額按 SN9 市场报价估算，并保留报价时间提示。其他代币没有已支持的价格来源时，只显示原单位。价格请求失败不能把已有代币数量变成零，也不能编造美元估值。",
      "## 为什么设备顶部只显示部分收益？",
      "某个项目只有钱包汇总、月度积分、旧记录或未知金額时，不会进入设备今日总收益。打开卡片项目明细，核对来源、记录周期和原单位。详细步骤见 [IOTA 收益计算](/learn/how-rewards-work)。",
    ],
    [
      "## 合計前，先核對三個條件",
      "同一幣種、統計週期與資料歸屬，才有比較或合計的基礎。餘額是某個時點的存量，今日收益是週期內的增量；積分、任務數及權重不能直接當作現金收入。",
      "## 今日、UTC 日與近 24 小時有何不同？",
      "IOTA 與 Vast.ai 今日統計使用香港時間日界，io.net 區塊獎勵使用 UTC 日，Golem 為滾動的近 24 小時。跨午夜或比較機器時先看週期標籤，fly.ai 積分按對應月份閱讀。",
      "## 如何處理美元估值與缺失價格？",
      "IOTA 美元金額依 SN9 市場報價估算並標明時間。其他代幣沒有支援的價格來源時，僅顯示原單位。行情失敗不會把已有代幣數量變成零，也不會編造美元金額。",
      "## 為何設備頂部只有部分收益？",
      "錢包彙總、月度積分、舊紀錄或未知金額不計入設備今日合計。展開專案明細，核對來源、週期與原單位。可參考 [IOTA 收益計算](/learn/how-rewards-work)。",
    ],
    [
      "## Check three conditions before summing",
      "Currency, reporting period and attribution must match before figures can be compared or summed. A balance is a snapshot; daily income is an amount over a period. Points, task counts and network weights are not cash revenue.",
      "## How do today, a UTC day and rolling 24 hours differ?",
      "IOTA and Vast.ai use the Hong Kong day for daily figures; io.net block rewards use a UTC day; Golem uses a rolling 24-hour window. Read period labels before crossing midnight or comparing machines. fly.ai points belong to a specific month.",
      "## How are USD estimates and missing prices handled?",
      "IOTA's USD amount is estimated using the SN9 market quote with its time shown. Tokens without a supported price source keep their native unit. A failed price request does not turn a known token amount into zero and does not produce an invented USD estimate.",
      "## Why is the device headline only a partial total?",
      "Wallet totals, monthly points, old records and unknown amounts are excluded from device daily earnings. Expand project details to check the source, period and native unit. See [IOTA reward calculations](/learn/how-rewards-work) for the accounting rules.",
    ],
    [
      "## 합산 전 세 가지 조건을 확인하세요",
      "통화, 집계 기간과 귀속 범위가 일치해야 비교하거나 합산할 수 있습니다. 잔액은 특정 시점의 값이고 일일 수익은 기간 내 증가량입니다. 포인트, 작업 수와 네트워크 가중치는 현금 수익이 아닙니다.",
      "## 오늘, UTC 날짜, 최근 24시간은 어떻게 다른가요?",
      "IOTA·Vast.ai 일일 지표는 홍콩 날짜, io.net 블록 보상은 UTC 날짜, Golem은 최근 24시간을 사용합니다. 자정을 넘거나 기기를 비교하기 전 기간 표시를 확인하세요. fly.ai 포인트는 해당 월의 값입니다.",
      "## USD 추정과 가격 누락은 어떻게 처리하나요?",
      "IOTA USD 금액은 SN9 시세로 추정하고 시각을 표시합니다. 지원하는 가격 출처가 없는 토큰은 원래 단위를 유지합니다. 가격 조회 실패가 토큰 수량 0을 의미하거나 USD 금액을 임의로 만들지는 않습니다.",
      "## 기기 상단 합계가 일부 수익만 표시하는 이유는 무엇인가요?",
      "지갑 합계, 월간 포인트, 이전 기록과 알 수 없는 금액은 기기 일일 수익에서 제외합니다. 프로젝트 상세에서 출처, 기간과 단위를 확인하고 [IOTA 보상 계산](/learn/how-rewards-work)도 참고하세요.",
    ],
    [
      "## 合算前に3つの条件を確認します",
      "通貨、集計期間、帰属範囲が一致して初めて比較や合算ができます。残高はある時点の値で、日次収益は期間内の増分です。ポイント、ジョブ数、ネットワーク重みは現金収益ではありません。",
      "## 本日、UTC日、直近24時間はどう違いますか？",
      "IOTA・Vast.aiの日次指標は香港の日界、io.netブロック報酬はUTC日、Golemは直近24時間を使います。日付が変わる時や機器を比べる時は期間ラベルを確認します。fly.aiのポイントは対象月の値です。",
      "## USD推計と価格の欠損はどう扱いますか？",
      "IOTAのUSD額はSN9市場価格で推計し時刻を示します。対応する価格出典がないトークンは元の単位で表示します。価格取得の失敗で既知の数量をゼロにしたり、USD額を作り出したりはしません。",
      "## デバイス上部が一部の合計になるのはなぜ？",
      "ウォレット合計、月間ポイント、古い記録、不明な額は日次合計に含めません。詳細で出典、期間、単位を確認し、[IOTAの報酬計算](/learn/how-rewards-work)も参照できます。",
    ],
  ]),
];
const descriptions = [
  localized([
    "用公开 Miner ID 集中查看多台 IOTA Train at Home Mac 的状态与收益，了解标识、账号同步和排查步骤。",
    "用公開 Miner ID 集中查看多台 IOTA Train at Home Mac 的狀態與收益，了解識別碼、帳號同步及排查步驟。",
    "Track multiple IOTA Train at Home Macs using public Miner IDs. Learn which IDs to add, how to sync your list and when to check the official app.",
    "공개 Miner ID로 여러 IOTA Mac을 확인하고 식별자, 목록 동기화와 문제 해결 방법을 알아보세요.",
    "公開Miner IDで複数のIOTA Macを確認し、IDの追加、一覧の同期、公式アプリでの対処を整理します。",
  ]),
  localized([
    "把同一台机器的 IOTA、XID、fly.ai 等项目关联到一张卡片，区分设备收益、钱包余额和月度积分。",
    "將同一台機器的 IOTA、XID、fly.ai 等專案關聯到一張卡片，區分設備收益、錢包餘額與月度積分。",
    "Link IOTA, XID, fly.ai and other identifiers to one device card. Keep device rewards, wallet balances and monthly points distinct.",
    "IOTA, XID, fly.ai 식별자를 기기 카드에 연결하고 기기 수익, 지갑 잔액과 월간 포인트를 구별하세요.",
    "IOTA、XID、fly.aiなどを1枚の機器カードに紐付け、報酬、ウォレット残高、月間ポイントを区別します。",
  ]),
  localized([
    "按操作场景选择 IOTA Watch 或官方面板：集中监控与清单整理，或安装、启停任务、日志和收益领取。",
    "依操作情境選擇 IOTA Watch 或官方面板：集中監控與清單整理，或安裝、啟停任務、日誌及收益領取。",
    "Choose between IOTA Watch and official dashboards for saved-device monitoring, installation, runtime logs, account actions and reward claims.",
    "기기 모니터링, 설치, 실행 로그, 계정 작업과 보상 수령에 맞는 도구를 선택하세요.",
    "一覧の監視、導入、実行ログ、アカウント操作、報酬受領に応じて適切なツールを選びます。",
  ]),
  localized([
    "核对 IOTA、Vast.ai、io.net、Golem 和 fly.ai 的收益周期、币种及归属，理解今日总收益与部分收益。",
    "核對 IOTA、Vast.ai、io.net、Golem 與 fly.ai 的收益週期、幣種及歸屬，理解今日合計與部分收益。",
    "Compare reward periods, currencies and attribution across IOTA, Vast.ai, io.net, Golem and fly.ai before interpreting a device earnings total.",
    "IOTA, Vast.ai, io.net, Golem과 fly.ai의 집계 기간, 통화와 기기 귀속을 비교하세요.",
    "IOTA、Vast.ai、io.net、Golem、fly.aiの期間、通貨、帰属を確認して収益合計を読み解きます。",
  ]),
];
export const problemGuides: Article[] = problemLinks.map((p, i) => ({
  slug: p.path.slice("learn/".length),
  project: "all",
  published: DISCOVERY_UPDATED,
  modified: DISCOVERY_UPDATED,
  title: p.q,
  description: descriptions[i]!,
  summary: p.a,
  topic: localized([
    "使用场景",
    "使用情境",
    "Monitoring questions",
    "모니터링 질문",
    "監視の使い方",
  ]),
  body: Object.fromEntries(LOCALES.map((l) => [l, bodies[i]![l]])) as Article["body"],
  questions: Object.fromEntries(
    LOCALES.map((l) => [
      l,
      (
        [
          [4, 6],
          [3, 4],
          [4, 5],
          [1, 6],
        ][i] ?? []
      ).map((n) => productQuestions(l)[n]!),
    ]),
  ) as NonNullable<Article["questions"]>,
  related: problemLinks.filter((q) => q.id !== p.id).map((q) => q.path.slice(6)),
  sources: [
    { name: "IOTA Watch source and deployment", url: "https://github.com/molimao/iota" },
    {
      name: "IOTA Train at Home official guide",
      url: "https://docs.macrocosmos.ai/product-and-services/tah/tah-user-guide",
    },
  ],
  keywords: localized([
    ["挖矿监控", "多设备收益", "IOTA Watch"],
    ["挖礦監控", "多設備收益", "IOTA Watch"],
    ["mining monitoring", "multi-device rewards", "IOTA Watch"],
    ["채굴 모니터링", "여러 기기 수익", "IOTA Watch"],
    ["採掘の監視", "複数デバイスの収益", "IOTA Watch"],
  ]),
}));

problemGuides[2]!.comparison = localized([
  {
    headers: ["要做的事", "IOTA Watch", "官方工具"],
    rows: [
      ["保存多台设备标识", "按名称与项目整理清单", "功能与保存方式因项目而异"],
      ["核对记录来源与时间", "查看来源及最近成功读取时间", "查看原项目记录和规则"],
      ["安装或启停任务", "提供监控查询", "在官方应用或节点工具操作"],
      ["领取或转出收益", "查看可用记账记录", "按原项目的支付规则处理"],
    ],
  },
  {
    headers: ["要做的事", "IOTA Watch", "官方工具"],
    rows: [
      ["儲存多台設備識別碼", "依名稱與專案整理清單", "功能與儲存方式因專案而異"],
      ["核對來源與時間", "查看來源與最近成功取得時間", "查看原專案紀錄與規則"],
      ["安裝或啟停任務", "提供監控查詢", "在官方應用或節點工具操作"],
      ["領取或轉出收益", "查看可用記帳紀錄", "依原專案支付規則處理"],
    ],
  },
  {
    headers: ["Task", "IOTA Watch", "Official tools"],
    rows: [
      [
        "Keep multiple identifiers",
        "Organize by device name and project",
        "Features and storage vary by project",
      ],
      [
        "Check source and timing",
        "Source and last successful fetch time",
        "Original project records and rules",
      ],
      ["Install or control jobs", "Monitoring lookups", "Official app or node tools"],
      [
        "Claim or transfer rewards",
        "Available accounted records",
        "Original project's payment rules",
      ],
    ],
  },
  {
    headers: ["작업", "IOTA Watch", "공식 도구"],
    rows: [
      ["여러 식별자 저장", "기기 이름과 프로젝트별 정리", "프로젝트별 기능·저장 방식"],
      ["출처와 시각 확인", "출처와 마지막 조회 시각", "원래 기록과 프로젝트 규칙"],
      ["설치·작업 제어", "모니터링 조회", "공식 앱 또는 노드 도구"],
      ["보상 수령·전송", "조회 가능한 정산 기록", "원래 프로젝트의 결제 규칙"],
    ],
  },
  {
    headers: ["目的", "IOTA Watch", "公式ツール"],
    rows: [
      ["複数IDの保存", "機器名とプロジェクトで整理", "機能・保存方法はプロジェクトごとに異なる"],
      ["出典と時刻の確認", "出典と最終取得時刻", "元の記録とプロジェクトの規則"],
      ["導入・ジョブ操作", "監視の照会", "公式アプリ・ノードツール"],
      ["報酬の受取・転送", "取得可能な記帳記録", "元のプロジェクトの支払規則"],
    ],
  },
]);
