import { localized as l } from "@/lib/product-discovery";
export const reportCopy = {
  value: l([
    "昨日收益，每天发到邮箱",
    "昨日收益，每天寄到信箱",
    "Yesterday’s earnings, emailed daily",
    "어제 수익을 매일 이메일로",
    "昨日の収益を毎日メールで",
  ]),
  settings: l([
    "设置日报",
    "設定日報",
    "Set up daily emails",
    "일일 이메일 설정",
    "日次メールを設定",
  ]),
  viewPro: l(["查看 Pro", "查看 Pro", "View Pro", "Pro 보기", "Proを見る"]),
  included: l([
    "Pro 订阅包含收益日报",
    "Pro 訂閱包含收益日報",
    "Daily reports are included in Pro",
    "Pro에 일일 수익 보고서 포함",
    "Proに日次収益レポートを含む",
  ]),
  paywallIntro: l([
    "更多设备名额，加上每日收益邮件。",
    "更多設備名額，加上每日收益郵件。",
    "More devices, plus daily earnings emails.",
    "기기 한도 확대와 일일 수익 이메일.",
    "デバイス枠の拡張と日次収益メール。",
  ]),
  afterPayment: l([
    "付款后，在「我的 Pro」开启日报，次日开始发送。",
    "付款後，在「我的 Pro」開啟日報，次日開始寄送。",
    "After payment, enable daily emails in My Pro. Sending starts the next day.",
    "결제 후 내 Pro에서 일일 이메일을 켜면 다음 날부터 전송합니다.",
    "支払い後、マイ Proで日次メールを有効にすると翌日から送信します。",
  ]),
  devices: l(["台设备", "台設備", "devices", "대 기기", "台のデバイス"]),
  projects: l(["个项目", "個專案", "projects", "개 프로젝트", "プロジェクト"]),
  title: l([
    "每日收益邮件",
    "每日收益郵件",
    "Daily earnings email",
    "일일 수익 이메일",
    "日次収益メール",
  ]),
  schedule: l([
    "每天 09:30 · 北京时间",
    "每天 09:30 · 北京時間",
    "Daily 09:30 · Beijing time",
    "매일 09:30 · 베이징 시간",
    "毎日09:30・北京時間",
  ]),
  intro: l([
    "汇总昨日收益，按项目分别展示。",
    "彙總昨日收益，依專案分別顯示。",
    "Yesterday’s earnings, grouped by project.",
    "어제 수익을 프로젝트별로 확인합니다.",
    "昨日の収益をプロジェクト別に表示します。",
  ]),
  enable: l([
    "开启收益日报",
    "開啟收益日報",
    "Enable daily earnings emails",
    "일일 수익 이메일 켜기",
    "日次収益メールを有効にする",
  ]),
  subscribed: l(["已订阅", "已訂閱", "Subscribed", "구독 중", "購読中"]),
  unsubscribe: l([
    "关闭邮件日报",
    "關閉郵件日報",
    "Turn off daily emails",
    "일일 이메일 끄기",
    "日次メールを停止",
  ]),
  preview: l([
    "查看邮件样式",
    "查看郵件樣式",
    "Preview email",
    "이메일 미리보기",
    "メールをプレビュー",
  ]),
  pro: l(["Pro 专属", "Pro 專屬", "Pro feature", "Pro 전용", "Pro限定"]),
  recipient: l(["接收邮箱", "收件信箱", "Recipient", "수신 이메일", "受信先"]),
  language: l(["邮件语言", "郵件語言", "Email language", "이메일 언어", "メールの言語"]),
  next: l(["下次发送", "下次寄送", "Next send", "다음 전송", "次回送信"]),
  emailChanged: l([
    "邮箱已变更，请重新订阅。",
    "信箱已變更，請重新訂閱。",
    "Email changed. Please subscribe again.",
    "이메일이 변경되었습니다. 다시 구독하세요.",
    "メールアドレスが変更されました。再購読してください。",
  ]),
  first: l([
    "开启后从次日开始发送。可随时关闭。",
    "開啟後從次日開始寄送，可隨時關閉。",
    "Starts the next day. You can turn it off anytime.",
    "다음 날부터 전송하며 언제든 끌 수 있습니다.",
    "翌日から送信し、いつでも停止できます。",
  ]),
  inactive: l([
    "Pro 到期后自动暂停发送。",
    "Pro 到期後自動暫停寄送。",
    "Sending pauses when Pro expires.",
    "Pro 만료 시 전송이 중지됩니다.",
    "Proの期限が切れると送信を停止します。",
  ]),
  saving: l(["保存中…", "儲存中…", "Saving…", "저장 중…", "保存中…"]),
  failed: l([
    "保存失败，请重试。",
    "儲存失敗，請重試。",
    "Could not save. Try again.",
    "저장 실패. 다시 시도하세요.",
    "保存できませんでした。再試行してください。",
  ]),
  setup: l([
    "邮件服务尚未启用",
    "郵件服務尚未啟用",
    "Email service is not enabled yet",
    "이메일 서비스가 아직 활성화되지 않았습니다",
    "メールサービスはまだ有効ではありません",
  ]),
  yesterday: l(["昨日收益", "昨日收益", "Yesterday’s earnings", "어제 수익", "昨日の収益"]),
  estimate: l([
    "可估算收益",
    "可估算收益",
    "Available USD estimate",
    "산정 가능한 USD 수익",
    "算定可能なUSD換算",
  ]),
  estimateNote: l([
    "美元按本次查询报价估算。缺失项目不计入。",
    "美元依此次查詢報價估算，缺失專案不計入。",
    "USD uses the quote fetched for this report. Unavailable projects are excluded.",
    "USD는 보고서 조회 가격 기준이며 미조회 프로젝트는 제외합니다.",
    "USDは本レポート取得時の価格です。未取得の項目は含みません。",
  ]),
  project: l(["项目", "專案", "Project", "프로젝트", "プロジェクト"]),
  amount: l(["原币收益", "原幣收益", "Native amount", "토큰 수익", "ネイティブ数量"]),
  usd: l(["美元估值", "美元估值", "USD estimate", "USD 추정치", "USD換算"]),
  coverage: l(["数据覆盖", "資料覆蓋", "Coverage", "조회 범위", "取得範囲"]),
  unknown: l(["未获取", "未取得", "Unavailable", "미조회", "未取得"]),
  unsupported: l([
    "来源未提供昨日收益",
    "來源未提供昨日收益",
    "Source has no yesterday earnings",
    "소스에 어제 수익이 없습니다",
    "取得元に昨日の収益がありません",
  ]),
  differentPeriod: l([
    "统计周期不同，不计入昨日",
    "統計期間不同，不計入昨日",
    "Different period; excluded from yesterday",
    "기간이 달라 어제 수익에서 제외",
    "期間が異なるため昨日には算入しません",
  ]),
  connect: l([
    "需要连接项目账户",
    "需要連接專案帳戶",
    "Connect the project account",
    "프로젝트 계정 연결 필요",
    "プロジェクトのアカウント接続が必要",
  ]),
  partial: l(["部分数据", "部分資料", "Partial data", "일부 데이터", "一部のデータ"]),
  known: l([
    "已知美元估值构成",
    "已知美元估值組成",
    "Known USD estimate breakdown",
    "확인된 USD 추정치 구성",
    "取得済みUSD換算の内訳",
  ]),
  window: l([
    "统计范围：昨日 00:00 至今日 00:00（北京时间）。IOTA 按记账日期统计。",
    "統計範圍：昨日 00:00 至今日 00:00（北京時間），IOTA 依記帳日期統計。",
    "Window: yesterday 00:00 to today 00:00, Beijing time. IOTA follows accounting dates.",
    "베이징 기준 어제 00:00부터 오늘 00:00까지이며 IOTA는 기록 날짜 기준입니다.",
    "北京時間の昨日00:00から今日00:00まで。IOTAは記帳日で集計します。",
  ]),
  generated: l(["读取时间", "讀取時間", "Retrieved at", "조회 시각", "取得時刻"]),
  quoteTime: l([
    "美元报价时间",
    "美元報價時間",
    "USD quote time",
    "USD 가격 시각",
    "USD価格の取得時刻",
  ]),
  open: l([
    "查看我的设备",
    "查看我的設備",
    "View my devices",
    "내 기기 보기",
    "マイデバイスを見る",
  ]),
  reason: l([
    "你已开启 Pro 每日收益邮件。",
    "你已開啟 Pro 每日收益郵件。",
    "You enabled Pro daily earnings emails.",
    "Pro 일일 수익 이메일을 활성화했습니다.",
    "Proの日次収益メールを有効にしています。",
  ]),
  demo: l([
    "邮件预览 · 演示数据",
    "郵件預覽 · 示範資料",
    "Email preview · Sample data",
    "이메일 미리보기 · 예시 데이터",
    "メールプレビュー・サンプルデータ",
  ]),
  confirm: l([
    "确认关闭日报",
    "確認關閉日報",
    "Confirm unsubscribe",
    "구독 해제 확인",
    "購読停止を確認",
  ]),
  stopped: l([
    "日报已关闭",
    "日報已關閉",
    "Daily emails turned off",
    "일일 이메일이 꺼졌습니다",
    "日次メールを停止しました",
  ]),
  privacy: l([
    "每日收益邮件需要你主动开启，接收地址为已验证的登录邮箱。我们会将邮箱和你的项目收益报表交给邮件服务商用于发送；不附带私钥或项目读取凭据。报表快照保留 7 天用于发送重试和排错。你可以在账号页面或邮件退订链接关闭；Pro 到期后暂停发送。",
    "每日收益郵件需主動開啟，寄至已驗證的登入信箱。信箱與專案收益報表會交給郵件服務商寄送，不含私鑰或專案讀取憑證。報表快照保留 7 天供重試及排錯，可由帳戶頁或郵件退訂連結關閉；Pro 到期後暫停。",
    "Daily reports are opt-in and use your verified sign-in email. The email provider processes that address and your project earnings report for delivery; private keys and project read credentials are excluded. Report snapshots are retained for 7 days for retry and troubleshooting. Disable them in your account or through the email unsubscribe link. Sending pauses when Pro expires.",
    "일일 보고서는 직접 활성화하며 인증된 로그인 이메일로 보냅니다. 발송을 위해 이메일 제공업체에 주소와 프로젝트 수익 보고서를 전달하며 비밀키·프로젝트 조회 인증 정보는 포함하지 않습니다. 재시도·문제 확인을 위해 스냅샷을 7일 보관합니다. 계정 페이지나 이메일 링크로 해제할 수 있고 Pro 만료 시 전송이 중지됩니다.",
    "日次レポートは自分で有効にし、確認済みのログインメールへ送信します。配信のためメール事業者へ宛先とプロジェクト収益レポートを渡しますが、秘密鍵やプロジェクトの読取認証は含めません。再試行・調査用の記録は7日間保持します。アカウント画面やメールの停止リンクで解除でき、Pro期限切れで送信を停止します。",
  ]),
};
