import type { SiteLocale } from "@/lib/site";

const labels = {
  importPartial: [
    "部分设备未导入；原本的本地清单已保留，可检查项目名额后重试。",
    "Some devices could not be imported. The original local list is retained; check project quotas and retry.",
    "部分設備未匯入；原本的本地清單已保留，可檢查項目名額後重試。",
    "일부 기기를 가져오지 못했습니다. 원래 로컬 목록은 유지됩니다. 프로젝트 한도를 확인하고 다시 시도하세요.",
    "一部のデバイスを取り込めませんでした。元のローカル一覧は保持。プロジェクトの枠を確認して再試行してください。",
  ],
  expand: [
    "扩展项目设备名额",
    "More devices per project",
    "擴展項目設備名額",
    "프로젝트별 기기 한도 확장",
    "プロジェクトのデバイス枠を拡張",
  ],
  quotaFull: [
    "{project} 的免费名额已用满",
    "{project}'s Free quota is full",
    "{project} 的免費名額已用滿",
    "{project}의 무료 한도가 찼습니다",
    "{project} の無料枠が上限に達しました",
  ],
  used: ["已关联", "Linked", "已關聯", "연결됨", "関連付け済み"],
  additional: [
    "每个项目增加 45 个设备名额",
    "45 more device slots in each project",
    "每個項目增加 45 個設備名額",
    "각 프로젝트에 기기 45대 추가",
    "各プロジェクトで45台分の枠を追加",
  ],
  sameMonitoring: [
    "免费版和 Pro 的监控功能相同",
    "The same monitoring features on Free and Pro",
    "免費版和 Pro 的監控功能相同",
    "무료와 Pro의 모니터링 기능은 동일합니다",
    "無料と Pro の監視機能は共通",
  ],
  annualSave: [
    "比月付省 {percent}%",
    "Save {percent}% vs monthly",
    "比月付省 {percent}%",
    "월간 대비 {percent}% 절약",
    "月払いより {percent}% お得",
  ],
  annualEquivalent: [
    "折合 US${amount} / 月",
    "Equivalent to US${amount} / month",
    "折合 US${amount} / 月",
    "월 US${amount} 상당",
    "月あたり US${amount} 相当",
  ],
  annualCharge: [
    "每年一次收取 US$16.90，自动续费",
    "US$16.90 charged once a year; renews automatically",
    "每年一次收取 US$16.90，自動續費",
    "연 1회 US$16.90 청구, 자동 갱신",
    "年1回 US$16.90 を請求、自動更新",
  ],
  monthlyCharge: [
    "每月收取 US$2.90，自动续费",
    "US$2.90 charged monthly; renews automatically",
    "每月收取 US$2.90，自動續費",
    "매월 US$2.90 청구, 자동 갱신",
    "毎月 US$2.90 を請求、自動更新",
  ],
  continueFree: [
    "继续使用免费版",
    "Continue with Free",
    "繼續使用免費版",
    "무료 버전 계속 사용",
    "無料版を続ける",
  ],
  checkout: [
    "继续至 Stripe 支付",
    "Continue to Stripe checkout",
    "繼續至 Stripe 付款",
    "Stripe 결제로 이동",
    "Stripe の決済へ",
  ],
  stripePayment: [
    "付款由 Stripe 处理，本站不保存银行卡信息。",
    "Stripe processes payment; this site does not store card details.",
    "付款由 Stripe 處理，本站不保存銀行卡資訊。",
    "결제는 Stripe에서 처리하며 사이트는 카드 정보를 저장하지 않습니다.",
    "決済は Stripe が処理し、当サイトにカード情報は保存しません。",
  ],
  previewWall: [
    "预览付费墙",
    "Preview upgrade dialog",
    "預覽付費牆",
    "업그레이드 화면 미리보기",
    "アップグレード画面を確認",
  ],
  viewPro: ["查看 Pro", "View Pro", "查看 Pro", "Pro 보기", "Pro を見る"],
  manage: ["管理订阅", "Manage subscription", "管理訂閱", "구독 관리", "契約を管理"],
  rename: ["编辑设备", "Edit device", "編輯設備", "기기 편집", "デバイスを編集"],
  merge: [
    "合并到此设备",
    "Merge into this device",
    "合併到此設備",
    "이 기기로 병합",
    "このデバイスに統合",
  ],
  remove: ["移除设备", "Remove device", "移除設備", "기기 제거", "デバイスを削除"],
  unlink: ["解除关联", "Unlink project", "解除關聯", "프로젝트 연결 해제", "関連付けを解除"],
  removeNote: [
    "只移除监控清单中的记录，不操作实际矿工。",
    "Removes the monitoring record only; it does not operate the miner.",
    "只移除監控清單中的記錄，不操作實際礦工。",
    "모니터링 기록만 제거하며 채굴기를 조작하지 않습니다.",
    "監視リストの記録のみ削除し、マイナーは操作しません。",
  ],
  mergeNote: [
    "请确认两条记录属于同一台实际设备。项目关联会移到当前设备。",
    "Confirm both records are the same physical machine. Project links move to this device.",
    "請確認兩條記錄屬於同一台實際設備。項目關聯會移到目前設備。",
    "두 기록이 동일한 물리적 기기인지 확인하세요. 프로젝트 연결이 이 기기로 이동합니다.",
    "両方の記録が同じ実機であることを確認。関連付けはこのデバイスに移動します。",
  ],
  balance: ["钱包余额", "Wallet balance", "錢包餘額", "지갑 잔액", "ウォレット残高"],
  monthPoints: ["本月积分", "This month's points", "本月積分", "이번 달 포인트", "今月のポイント"],
  monthShare: [
    "本月积分占比",
    "Share of monthly points",
    "本月積分佔比",
    "월간 포인트 비율",
    "月間ポイントの割合",
  ],
  stale: ["旧数据", "Cached data", "舊資料", "이전 데이터", "過去のデータ"],
  signIn: [
    "登录并跨设备同步",
    "Sign in to sync across devices",
    "登入並跨設備同步",
    "로그인하여 기기 간 동기화",
    "ログインしてデバイス間で同期",
  ],
  importLocal: [
    "导入此浏览器的设备",
    "Import this browser's devices",
    "匯入此瀏覽器的設備",
    "이 브라우저의 기기 가져오기",
    "このブラウザーのデバイスを取り込む",
  ],
  savedLocal: [
    "保存在当前浏览器",
    "Saved in this browser",
    "保存在目前瀏覽器",
    "이 브라우저에 저장됨",
    "このブラウザーに保存",
  ],
  savedAccount: [
    "已同步到账号",
    "Synced to your account",
    "已同步到帳號",
    "계정에 동기화됨",
    "アカウントに同期済み",
  ],
  checking: [
    "正在读取账号数据",
    "Reading account data",
    "正在讀取帳號資料",
    "계정 데이터를 읽는 중",
    "アカウント情報を読み込み中",
  ],
  paymentPending: [
    "支付结果正在核验，请稍后查看套餐状态。",
    "Payment is being verified. Check the plan status shortly.",
    "付款結果正在核驗，請稍後查看方案狀態。",
    "결제를 확인 중입니다. 잠시 후 요금제 상태를 확인하세요.",
    "決済を確認中です。しばらくしてプランをご確認ください。",
  ],
  apiLimited: [
    "公开接口未提供设备实时状态",
    "The public API does not provide live device status",
    "公開介面未提供設備即時狀態",
    "공개 API는 기기의 실시간 상태를 제공하지 않습니다",
    "公開 API はデバイスのリアルタイム状態を提供していません",
  ],
  title: ["设备总览", "Device overview", "設備總覽", "기기 개요", "デバイス一覧"],
  intro: [
    "在一张卡片里查看同一台设备的所有项目。",
    "All projects on the same machine, together in one card.",
    "在一張卡片裡查看同一台設備的所有項目。",
    "같은 기기의 모든 프로젝트를 한 카드에서 확인하세요.",
    "同じデバイスの全プロジェクトを1枚のカードで確認。",
  ],
  preview: [
    "设计预览 · 示例数据 · 尚未发布",
    "Design preview · Sample data · Not published",
    "設計預覽 · 範例資料 · 尚未發布",
    "디자인 미리보기 · 예시 데이터 · 미게시",
    "デザインプレビュー · サンプルデータ · 未公開",
  ],
  devices: ["设备", "Devices", "設備", "기기", "デバイス"],
  projects: ["项目", "Projects", "項目", "프로젝트", "プロジェクト"],
  plans: ["套餐与订阅", "Plans & billing", "方案與訂閱", "요금제 및 구독", "プランと契約"],
  all: ["全部项目", "All projects", "全部項目", "모든 프로젝트", "全プロジェクト"],
  search: [
    "搜索设备、型号或项目",
    "Search devices, hardware or projects",
    "搜尋設備、型號或項目",
    "기기, 하드웨어 또는 프로젝트 검색",
    "デバイス・機種・プロジェクトを検索",
  ],
  add: ["添加设备", "Add device", "新增設備", "기기 추가", "デバイスを追加"],
  link: ["关联项目", "Link project", "關聯項目", "프로젝트 연결", "プロジェクトを関連付け"],
  linked: ["已关联项目", "Linked projects", "已關聯項目", "연결된 프로젝트", "関連付け済み"],
  free: ["免费", "Free", "免費", "무료", "無料"],
  perProject: [
    "每个项目独立计数",
    "Counted separately per project",
    "每個項目獨立計數",
    "프로젝트별로 독립 집계",
    "プロジェクトごとに個別計上",
  ],
  noFleetLimit: [
    "设备总览无额外总数限制",
    "No separate limit on the device overview",
    "設備總覽無額外總數限制",
    "기기 개요에는 별도 총수 제한이 없습니다",
    "デバイス一覧に別途の総数上限はありません",
  ],
  today: ["今日收益", "Today's rewards", "今日收益", "오늘 보상", "本日の報酬"],
  usdEstimate: ["美元估值", "USD estimate", "美元估值", "USD 추정치", "米ドル換算目安"],
  total: ["累计收益", "Lifetime rewards", "累計收益", "누적 보상", "累計報酬"],
  wallet: ["钱包汇总", "Wallet total", "錢包彙總", "지갑 합계", "ウォレット合計"],
  walletNote: [
    "钱包数据可能包含多台设备，不计入设备收益合计。",
    "Wallet figures may include other machines and are excluded from device reward totals.",
    "錢包資料可能包含多台設備，不計入設備收益合計。",
    "지갑 데이터에는 다른 기기가 포함될 수 있으며 기기 보상 합계에 더하지 않습니다.",
    "ウォレットの値は他の機器を含む場合があるため、デバイス報酬の合計には加算しません。",
  ],
  details: ["查看明细", "View details", "查看明細", "상세 보기", "詳細を見る"],
  name: ["设备名称", "Device name", "設備名稱", "기기 이름", "デバイス名"],
  hardware: [
    "设备型号（选填）",
    "Hardware (optional)",
    "設備型號（選填）",
    "하드웨어 (선택)",
    "機種（任意）",
  ],
  identifier: [
    "公开 Miner ID / 钱包地址",
    "Public Miner ID / wallet address",
    "公開 Miner ID / 錢包地址",
    "공개 Miner ID / 지갑 주소",
    "公開 Miner ID / ウォレットアドレス",
  ],
  worker: [
    "Worker 名称（选填）",
    "Worker name (optional)",
    "Worker 名稱（選填）",
    "Worker 이름 (선택)",
    "Worker 名（任意）",
  ],
  choose: ["选择设备", "Choose device", "選擇設備", "기기 선택", "デバイスを選択"],
  mapping: [
    "确认这是同一台设备后再关联。相同用户名不会自动合并设备。",
    "Link only after confirming the same physical machine. Matching usernames do not automatically merge devices.",
    "確認這是同一台設備後再關聯。相同使用者名稱不會自動合併設備。",
    "동일한 물리적 기기인지 확인한 후 연결하세요. 사용자 이름이 같아도 기기를 자동으로 병합하지 않습니다.",
    "同じ物理デバイスであると確認してから関連付けてください。同名ユーザーのデバイスは自動統合しません。",
  ],
  save: ["保存", "Save", "儲存", "저장", "保存"],
  cancel: ["取消", "Cancel", "取消", "취소", "キャンセル"],
  empty: [
    "没有匹配的设备",
    "No matching devices",
    "沒有符合的設備",
    "일치하는 기기가 없습니다",
    "該当するデバイスはありません",
  ],
  unavailable: ["未获取", "Unavailable", "未取得", "확인 불가", "取得できません"],
  training: ["有训练贡献", "Contributing", "有訓練貢獻", "학습 기여 중", "学習に貢献中"],
  waiting: ["等待任务", "Waiting for jobs", "等待任務", "작업 대기", "タスク待機"],
  mining: [
    "有算力上报",
    "Hashrate reported",
    "有算力回報",
    "해시레이트 보고됨",
    "ハッシュレート報告済み",
  ],
  source: ["数据来源", "Data source", "資料來源", "데이터 출처", "データソース"],
  quotas: [
    "项目设备名额",
    "Devices per project",
    "項目設備名額",
    "프로젝트별 기기 한도",
    "プロジェクトごとのデバイス枠",
  ],
  month: ["月付", "Monthly", "月付", "월간", "月払い"],
  year: ["年付", "Annual", "年付", "연간", "年払い"],
  perMonth: ["/ 月", "/ month", "/ 月", "/ 월", "/ 月"],
  perYear: ["/ 年", "/ year", "/ 年", "/ 년", "/ 年"],
  upTo: [
    "每个项目最多",
    "Up to, per project",
    "每個項目最多",
    "프로젝트별 최대",
    "各プロジェクトの上限",
  ],
  choosePlan: ["选择 Pro", "Choose Pro", "選擇 Pro", "Pro 선택", "Pro を選択"],
  current: ["当前套餐", "Current plan", "目前方案", "현재 요금제", "現在のプラン"],
  renewal: [
    "自动续费，可在订阅管理中取消。取消后权益保留至已付费周期结束。",
    "Renews automatically. Cancel in billing management; access continues through the paid period.",
    "自動續費，可在訂閱管理中取消。取消後權益保留至已付費週期結束。",
    "자동 갱신되며 구독 관리에서 취소할 수 있습니다. 혜택은 결제 기간 종료까지 유지됩니다.",
    "自動更新。契約管理で解約でき、お支払い済みの期間終了まで利用できます。",
  ],
  downgrade: [
    "到期后超过免费名额的设备仍可查看，新增设备受对应项目名额限制。",
    "After expiry, existing devices remain visible. Adding devices is limited separately in each project.",
    "到期後超過免費名額的設備仍可查看，新增設備受對應項目名額限制。",
    "만료 후에도 기존 기기는 볼 수 있습니다. 새 기기 추가에는 프로젝트별 한도가 적용됩니다.",
    "期限後も既存デバイスを表示。追加時は各プロジェクトの上限が適用されます。",
  ],
  previewBilling: [
    "预览不会发起付款，正式订阅尚未开放。",
    "This preview does not initiate payment. Live subscriptions are not open yet.",
    "預覽不會發起付款，正式訂閱尚未開放。",
    "미리보기에서는 결제를 시작하지 않습니다. 실제 구독은 아직 열리지 않았습니다.",
    "プレビューでは決済しません。正式な契約受付はまだ開始していません。",
  ],
  sameFeatures: [
    "跨项目设备总览 · 各项目独立监控 · 数据时间与来源",
    "Cross-project overview · Project monitoring · Source & freshness",
    "跨項目設備總覽 · 各項目獨立監控 · 資料時間與來源",
    "프로젝트 통합 개요 · 개별 모니터링 · 데이터 출처 및 갱신 시각",
    "横断デバイス一覧 · 個別監視 · データの出典と更新時刻",
  ],
  limit: [
    "该项目名额已满，可选择已关联该项目的设备或升级 Pro。",
    "This project's quota is full. Select an already linked device or upgrade to Pro.",
    "該項目名額已滿，可選擇已關聯該項目的設備或升級 Pro。",
    "이 프로젝트의 한도가 찼습니다. 이미 연결된 기기를 선택하거나 Pro로 업그레이드하세요.",
    "このプロジェクトの枠は満杯です。関連付け済みデバイスを選択するか Pro にアップグレードしてください。",
  ],
} as const;
export function fleetCopy(locale: SiteLocale) {
  const index = ({ zh: 0, en: 1, "zh-TW": 2, ko: 3, ja: 4 } as const)[locale];
  return Object.fromEntries(
    Object.entries(labels).map(([key, values]) => [key, values[index]]),
  ) as { [K in keyof typeof labels]: string };
}
