import type { SiteLocale } from "@/lib/site";
const labels = {
  identifier: {
    zh: "公开标识",
    en: "Public identifier",
    "zh-TW": "公開識別碼",
    ko: "공개 식별자",
    ja: "公開ID",
  },
  connect: {
    zh: "连接账户",
    en: "Connect account",
    "zh-TW": "連接帳戶",
    ko: "계정 연결",
    ja: "アカウント接続",
  },
  disconnect: {
    zh: "断开连接",
    en: "Disconnect",
    "zh-TW": "中斷連接",
    ko: "연결 해제",
    ja: "接続解除",
  },
  connected: {
    zh: "已连接",
    en: "Connected",
    "zh-TW": "已連接",
    ko: "연결됨",
    ja: "接続済み",
  },
  login: {
    zh: "登录后连接",
    en: "Sign in to connect",
    "zh-TW": "登入後連接",
    ko: "로그인 후 연결",
    ja: "ログインして接続",
  },
  key: {
    zh: "访问令牌 / API Key",
    en: "Access token / API key",
    "zh-TW": "存取權杖 / API Key",
    ko: "액세스 토큰 / API 키",
    ja: "アクセストークン / APIキー",
  },
  connectNote: {
    zh: "凭据在服务器加密保存，7 天后需重新连接；本站只查询数据。Vast.ai 请仅授予 machine_read 和 billing_read 权限。",
    en: "Credentials are encrypted on the server; reconnect after 7 days. This site only reads data. For Vast.ai grant only machine_read and billing_read.",
    "zh-TW":
      "憑證在伺服器加密儲存，7 天後需重新連接；本站僅查詢資料。Vast.ai 請只授予 machine_read 和 billing_read。",
    ko: "자격 증명은 서버에 암호화되어 저장되며 7일 후 다시 연결해야 합니다. 데이터 조회만 수행합니다. Vast.ai는 machine_read와 billing_read만 허용하세요.",
    ja: "認証情報はサーバーで暗号化保存され、7日後に再接続が必要です。データの読み取りのみ行います。Vast.aiにはmachine_readとbilling_readのみ許可してください。",
  },
  notConfigured: {
    zh: "账户连接暂未启用",
    en: "Account connections are not enabled yet",
    "zh-TW": "帳戶連接尚未啟用",
    ko: "계정 연결이 아직 활성화되지 않았습니다",
    ja: "アカウント接続はまだ有効ではありません",
  },
  expired: {
    zh: "授权已失效，请重新连接",
    en: "Authorization expired. Reconnect.",
    "zh-TW": "授權已失效，請重新連接",
    ko: "인증이 만료되었습니다. 다시 연결하세요",
    ja: "認証が失効しました。再接続してください",
  },
  notFound: {
    zh: "未找到该标识",
    en: "Identifier not found",
    "zh-TW": "找不到此識別碼",
    ko: "식별자를 찾을 수 없습니다",
    ja: "IDが見つかりません",
  },
  lookup: {
    zh: "查询",
    en: "Look up",
    "zh-TW": "查詢",
    ko: "조회",
    ja: "照会",
  },
  online: {
    zh: "来源报告在线",
    en: "Reported online",
    "zh-TW": "來源回報在線",
    ko: "온라인으로 보고됨",
    ja: "オンラインと報告",
  },
  offline: {
    zh: "来源报告离线",
    en: "Reported offline",
    "zh-TW": "來源回報離線",
    ko: "오프라인으로 보고됨",
    ja: "オフラインと報告",
  },
  unknown: {
    zh: "状态未提供",
    en: "Status not supplied",
    "zh-TW": "未提供狀態",
    ko: "상태 미제공",
    ja: "状態は未提供",
  },
  gpu: {
    zh: "GPU 数量",
    en: "GPU count",
    "zh-TW": "GPU 數量",
    ko: "GPU 수",
    ja: "GPU数",
  },
  activeGpu: {
    zh: "已分配 GPU",
    en: "Allocated GPUs",
    "zh-TW": "已分配 GPU",
    ko: "할당된 GPU",
    ja: "割り当て済みGPU",
  },
  cpu: {
    zh: "CPU 核心",
    en: "CPU cores",
    "zh-TW": "CPU 核心",
    ko: "CPU 코어",
    ja: "CPUコア",
  },
  hardware: {
    zh: "硬件",
    en: "Hardware",
    "zh-TW": "硬體",
    ko: "하드웨어",
    ja: "ハードウェア",
  },
  rolling24h: {
    zh: "近 24 小时收益",
    en: "Last 24 hours",
    "zh-TW": "近 24 小時收益",
    ko: "최근 24시간 수익",
    ja: "直近24時間の収益",
  },
  hkDay: {
    zh: "今日收益（香港时间）",
    en: "Today · Hong Kong time",
    "zh-TW": "今日收益（香港時間）",
    ko: "오늘 수익 · 홍콩 시간",
    ja: "今日の収益 · 香港時間",
  },
  utcDay: {
    zh: "今日区块奖励（UTC）",
    en: "Today’s block rewards · UTC",
    "zh-TW": "今日區塊獎勵（UTC）",
    ko: "오늘 블록 보상 · UTC",
    ja: "今日のブロック報酬 · UTC",
  },
  partial: {
    zh: "部分数据暂不可用",
    en: "Some data is unavailable",
    "zh-TW": "部分資料暫不可用",
    ko: "일부 데이터를 사용할 수 없습니다",
    ja: "一部データを取得できません",
  },
  readOnly: {
    zh: "官方授权说明",
    en: "Official access instructions",
    "zh-TW": "官方授權說明",
    ko: "공식 인증 안내",
    ja: "公式の認証手順",
  },
  provider: {
    zh: "提供商",
    en: "Provider",
    "zh-TW": "供應商",
    ko: "공급자",
    ja: "プロバイダー",
  },
  cloud: {
    zh: "云算力",
    en: "Cloud compute",
    "zh-TW": "雲算力",
    ko: "클라우드 컴퓨팅",
    ja: "クラウド計算",
  },
  rental: {
    zh: "GPU 出租",
    en: "GPU rental",
    "zh-TW": "GPU 出租",
    ko: "GPU 임대",
    ja: "GPUレンタル",
  },
  distributed: {
    zh: "分布式计算",
    en: "Distributed compute",
    "zh-TW": "分散式運算",
    ko: "분산 컴퓨팅",
    ja: "分散計算",
  },
  needConnection: {
    zh: "连接账户后查询设备",
    en: "Connect your account to query devices",
    "zh-TW": "連接帳戶後查詢設備",
    ko: "기기를 조회하려면 계정을 연결하세요",
    ja: "デバイス照会にはアカウントを接続してください",
  },
  sourceTime: {
    zh: "来源时间",
    en: "Source timestamp",
    "zh-TW": "來源時間",
    ko: "출처 시각",
    ja: "ソース時刻",
  },
  review: {
    zh: "示例数据 · 不代表实际收益",
    en: "Sample data · not actual earnings",
    "zh-TW": "範例資料 · 非實際收益",
    ko: "예시 데이터 · 실제 수익 아님",
    ja: "サンプルデータ · 実際の収益ではありません",
  },
  capacityOnly: {
    zh: "公开接口提供容量和状态，未提供收益",
    en: "Public capacity and status; earnings not supplied",
    "zh-TW": "公開容量與狀態，未提供收益",
    ko: "공개 용량과 상태 · 수익 미제공",
    ja: "公開容量と状態 · 収益は未提供",
  },
} as const;
export const platformCopy = (locale: SiteLocale) =>
  Object.fromEntries(Object.entries(labels).map(([k, v]) => [k, v[locale]])) as {
    [K in keyof typeof labels]: string;
  };
export const platformEditorial = {
  akash: {
    title: {
      zh: "Akash 提供商监控：GPU 容量与在线状态",
      en: "Akash provider monitor: GPU capacity and status",
      "zh-TW": "Akash 供應商監控：GPU 容量與在線狀態",
      ko: "Akash 공급자 모니터: GPU 용량과 상태",
      ja: "Akashプロバイダー監視：GPU容量と状態",
    },
    summary: {
      zh: "提供商状态与 GPU 容量",
      en: "Provider status and GPU capacity",
      "zh-TW": "供應商狀態與 GPU 容量",
      ko: "공급자 상태와 GPU 용량",
      ja: "プロバイダーの状態とGPU容量",
    },
    identity: {
      zh: "填写 akash1 开头的公开提供商地址。一个提供商可能管理多台服务器。",
      en: "Use the public provider address beginning akash1. One provider may manage multiple servers.",
      "zh-TW": "填寫 akash1 開頭的公開供應商地址。一個供應商可能管理多台伺服器。",
      ko: "akash1로 시작하는 공개 공급자 주소를 입력하세요. 공급자 하나가 여러 서버를 관리할 수 있습니다.",
      ja: "akash1で始まる公開プロバイダーアドレスを入力します。1つのプロバイダーが複数サーバーを管理する場合があります。",
    },
    coverage: {
      zh: "数据来自 Akash 官方索引，显示来源报告状态、GPU 容量和分配量。这是提供商范围，不等于单台设备。本次不从标价或容量推算收益。",
      en: "Data comes from Akash’s official index: reported status, GPU capacity and allocation. These are provider-wide figures, not one device. Revenue is not inferred from pricing or capacity.",
      "zh-TW":
        "資料來自 Akash 官方索引，呈現回報狀態、GPU 容量及分配量。這是供應商範圍，並非單台設備。本次不從標價或容量推算收益。",
      ko: "Akash 공식 인덱스의 보고 상태, GPU 용량과 할당량입니다. 단일 기기가 아닌 공급자 전체 수치이며 가격이나 용량으로 수익을 추정하지 않습니다.",
      ja: "Akash公式インデックスの報告状態、GPU容量、割り当て量です。単一機器ではなくプロバイダー全体の値で、価格や容量から収益を推定しません。",
    },
  },
  ionet: {
    title: {
      zh: "io.net 设备监控：GPU 信息与区块奖励",
      en: "io.net device monitor: GPU details and block rewards",
      "zh-TW": "io.net 設備監控：GPU 資訊與區塊獎勵",
      ko: "io.net 기기 모니터: GPU 정보와 블록 보상",
      ja: "io.netデバイス監視：GPU情報とブロック報酬",
    },
    summary: {
      zh: "GPU 信息与区块奖励",
      en: "GPU details and block rewards",
      "zh-TW": "GPU 資訊與區塊獎勵",
      ko: "GPU 정보와 블록 보상",
      ja: "GPU情報とブロック報酬",
    },
    identity: {
      zh: "填写官方 Device ID，并连接 IO Explorer 的访问令牌。不要填写钱包私钥。",
      en: "Use the official Device ID and connect an IO Explorer access token. Never use a wallet private key.",
      "zh-TW": "填寫官方 Device ID，並連接 IO Explorer 存取權杖。不要填寫錢包私鑰。",
      ko: "공식 Device ID와 IO Explorer 액세스 토큰을 사용합니다. 지갑 비밀키는 입력하지 마세요.",
      ja: "公式Device IDとIO Explorerアクセストークンを使います。ウォレットの秘密鍵は入力しません。",
    },
    coverage: {
      zh: "查询硬件信息和当日 UTC 区块奖励。区块奖励不包含所有租用收入；过去在线率和任务记录不能证明实时在线。令牌过期后需重新连接。",
      en: "Queries hardware and UTC-day block rewards. Block rewards do not include all rental income. Historical uptime and jobs do not prove current connectivity. Reconnect when the token expires.",
      "zh-TW":
        "查詢硬體資訊與 UTC 當日區塊獎勵。區塊獎勵不包含所有租用收入；歷史在線率及任務不證明即時在線。權杖失效後需重新連接。",
      ko: "하드웨어와 UTC 당일 블록 보상을 조회합니다. 블록 보상이 모든 임대 수입을 포함하지는 않습니다. 과거 가동률과 작업 기록은 현재 연결 상태의 증거가 아닙니다. 토큰 만료 시 다시 연결하세요.",
      ja: "ハードウェアとUTC当日のブロック報酬を照会します。全レンタル収入は含まれません。過去の稼働率やジョブは現在の接続状態を証明しません。トークン失効時は再接続が必要です。",
    },
  },
  vast: {
    title: {
      zh: "Vast.ai 主机监控：GPU 设备与出租收入",
      en: "Vast.ai host monitor: GPU machines and rental income",
      "zh-TW": "Vast.ai 主機監控：GPU 設備與出租收入",
      ko: "Vast.ai 호스트 모니터: GPU 기기와 임대 수입",
      ja: "Vast.aiホスト監視：GPU機器とレンタル収入",
    },
    summary: {
      zh: "主机信息与出租收入",
      en: "Host details and rental income",
      "zh-TW": "主機資訊與出租收入",
      ko: "호스트 정보와 임대 수입",
      ja: "ホスト情報とレンタル収入",
    },
    identity: {
      zh: "填写数字 Machine ID，连接仅有 machine_read 和 billing_read 权限的 API Key。无需授予交易或机器管理权限。",
      en: "Use the numeric Machine ID and an API key with machine_read and billing_read only. Trading and machine-management permissions are unnecessary.",
      "zh-TW":
        "填寫數字 Machine ID，連接只有 machine_read 與 billing_read 權限的 API Key。無需交易或機器管理權限。",
      ko: "숫자 Machine ID와 machine_read, billing_read 권한만 있는 API 키를 사용합니다. 거래나 기기 관리 권한은 필요하지 않습니다.",
      ja: "数値のMachine IDとmachine_read・billing_readのみを許可したAPIキーを使います。取引や機器管理の権限は不要です。",
    },
    coverage: {
      zh: "按机器查询香港时间今日的出租收入，汇总接口返回的 GPU、存储和带宽收入。它是收入记录，不扣除电费和硬件成本；账户余额不作为设备收益。",
      en: "Reads today’s per-machine rental income since Hong Kong midnight, summing reported GPU, storage and bandwidth earnings. This is revenue before electricity and hardware costs. Account balance is not treated as device earnings.",
      "zh-TW":
        "依機器查詢香港時間今日出租收入，彙總介面回傳的 GPU、儲存與頻寬收入。此為未扣電費和硬體成本的收入，帳戶餘額不視為設備收益。",
      ko: "홍콩 자정 이후 기기별 GPU·스토리지·대역폭 수입을 합산합니다. 전기료와 하드웨어 비용 차감 전 수입이며 계정 잔액을 기기 수익으로 취급하지 않습니다.",
      ja: "香港の午前0時以降の機器別GPU・ストレージ・帯域収入を合計します。電気代や機器費用控除前の収入であり、口座残高を機器収益には含めません。",
    },
  },
  golem: {
    title: {
      zh: "Golem 节点监控：运行状态与 GLM 收益",
      en: "Golem provider monitor: status and GLM earnings",
      "zh-TW": "Golem 節點監控：運行狀態與 GLM 收益",
      ko: "Golem 노드 모니터: 상태와 GLM 수익",
      ja: "Golemノード監視：状態とGLM収益",
    },
    summary: {
      zh: "节点状态与近 24 小时收益",
      en: "Node status and last-24-hour earnings",
      "zh-TW": "節點狀態與近 24 小時收益",
      ko: "노드 상태와 최근 24시간 수익",
      ja: "ノード状態と直近24時間の収益",
    },
    identity: {
      zh: "填写 yagna id show 显示的节点 ID（0x 开头），不要用收款钱包地址替代。",
      en: "Use the node ID from yagna id show, beginning 0x. Do not substitute the payout wallet address.",
      "zh-TW": "填寫 yagna id show 顯示的節點 ID（0x 開頭），不要以收款錢包地址代替。",
      ko: "yagna id show의 0x로 시작하는 노드 ID를 사용합니다. 지급 지갑 주소로 대체하지 마세요.",
      ja: "yagna id showに表示される0xで始まるノードIDを使います。受取ウォレットアドレスで代用しないでください。",
    },
    coverage: {
      zh: "来自 Golem Stats 的节点状态、硬件与 GLM 记录。近 24 小时为滚动周期，不等于香港时间今日，设备今日合计不累加这项。接口失败显示不可用，不记为零。",
      en: "Node status, hardware and GLM records come from Golem Stats. The rolling 24-hour window is not the Hong Kong calendar day and is excluded from device daily totals. API failures remain unavailable, not zero.",
      "zh-TW":
        "節點狀態、硬體及 GLM 紀錄來自 Golem Stats。近 24 小時是滾動區間，不等於香港今日，不列入設備今日合計。介面失敗顯示不可用，不視為零。",
      ko: "상태·하드웨어·GLM 기록은 Golem Stats에서 가져옵니다. 최근 24시간은 홍콩의 오늘과 다르므로 기기 일일 합계에서 제외합니다. API 실패는 0이 아닌 사용 불가로 표시합니다.",
      ja: "状態・ハードウェア・GLM記録はGolem Statsが出典です。直近24時間は香港の暦日と異なり、機器の日次合計から除外します。APIエラーはゼロではなく取得不可と表示します。",
    },
  },
} as const;
