import type { SiteLocale } from "@/lib/site";

const en = {
  monitor: "Mining monitor",
  independent:
    "Independent read-only monitoring for IOTA Train at Home, XID / MMM, Quantus and fly.ai. Not affiliated with these projects.",
  privacyData:
    "Free supports 5 devices per project; Pro supports 50 per project. Project quotas are independent, and the device overview has no additional total limit. Google sign-in syncs the list across devices; without signing in it stays in this browser.",
  projects: "Projects",
  title: "Choose your project",
  intro: "Training and mining, with separate status and reward records for each project.",
  iota: "Reported training activity, network slots and accounted IOTA rewards.",
  xid: "Monitor xCoin mining with MMM: pool workers, reported hashrate and chain records.",
  quantus: "Monitor Quantus mainnet blocks and QTC mining rewards by public wormhole address.",
  flyai: "Track fly.ai monthly compute points and wallet share with a public ETH reward address.",
  compute: "Compute points",
  open: "Open monitor",
  training: "AI training",
  mining: "Mining",
  mainnet: "Mainnet",
  network: "Network overview",
  mine: "My addresses",
  address: "Public reward address",
  label: "Name (optional)",
  add: "Save address",
  remove: "Remove",
  invalid: "Check the address and checksum. Use a public mainnet reward address.",
  duplicate: "This address is already saved.",
  limit:
    "You can save up to 5 devices per project on Free, or 50 per project on Pro for each project.",
  storage: "This browser could not save your address list. Check storage permissions.",
  local:
    "Free supports 5 devices per project; Pro supports 50 per project. Project quotas are independent, and the device overview has no additional total limit. Google sign-in syncs the list across devices; without signing in it stays in this browser.",
  noSecrets: "Public addresses only. Never enter a seed phrase, private key or inner hash.",
  empty: "Add your reward address to monitor its records.",
  refresh: "Refresh",
  refreshing: "Refreshing…",
  fetched: "Last fetched",
  sample: "Latest source record",
  unavailable: "Unavailable",
  cached: "Cached data",
  sourceOld:
    "The latest source record is over 10 minutes old. A successful refresh does not make it current.",
  failed: "The source could not refresh. Previous data keeps its original timestamp.",
  badData: "The source returned an unexpected format. Previous valid data is retained.",
  height: "Block height",
  chainHashrate: "Estimated chain hashrate",
  poolHashrate: "Observed pool hashrate",
  workers: "Visible active workers",
  accounts: "Indexed accounts",
  historicalMiners: "Addresses with mining rewards",
  interval: "Recent average block interval",
  seconds: "s",
  difficulty: "Difficulty by block",
  blockTrend: "Block intervals",
  chartNote: "Recent blocks from the source; this is not device performance history.",
  poolScope:
    "Worker data covers the explorer's observed pools, not every miner. A worker name is not proof of a physical device or its model.",
  quantusScope:
    "An address can receive rewards from several devices. Chain rewards cannot establish device count, current hashrate or online status. This index covers block rewards, not the pool’s full payment ledger.",
  records: "Recent blocks",
  block: "Block",
  time: "Time",
  reward: "Reward",
  miner: "Miner",
  explorer: "Open explorer",
  website: "Official website",
  guide: "Mining guide",
  sources: "Sources & data coverage",
  setup: "Get started",
  first: "Install the official miner",
  second: "Copy your public reward address",
  third: "Add the address here",
  xidStep:
    "Use the MMM setup guide for Apple Silicon. The selected pool determines which worker records are visible.",
  quantusStep:
    "Use the official Quantus mainnet guide. Wait for your node to sync before mining; Planck testnet records are separate.",
  publicStep:
    "XID uses an xpa1r address. Quantus mining uses a qz wormhole address; the inner hash stays on your device.",
  monitorStep:
    "Keep different reward addresses separate. Missing source data appears as unavailable.",
  worker: "Worker",
  hashrate: "Pool-estimated hashrate",
  reported: "Miner-reported hashrate",
  shares: "Accepted shares",
  lastSeen: "Last activity",
  noWorkers:
    "No worker records for this address in the fetched list. This does not prove the miner is offline.",
  balance: "Explorer balance",
  balanceNote:
    "Balance is not lifetime mining income. Check reward maturity and spendable funds in the official explorer or wallet.",
  blocks: "Chain-attributed blocks",
  notFound: "No indexed reward record for this address yet. Check the address and network.",
  today: "Today's indexed mining rewards",
  lifetime: "Lifetime indexed mining rewards",
  todayNote: "Since 00:00 Hong Kong time (UTC+8). Mining rewards are separate from wallet balance.",
  recentRewards: "Recent mining rewards",
  none: "No records returned.",
  poolOld: "Pool data is marked stale by the source.",
  back: "All projects",
  other: "More projects",
  overview: "Overview",
  export: "Export addresses",
  download: "Official downloads",
} as const;
type Copy = { [K in keyof typeof en]: string };
const zh: Copy = {
  monitor: "挖矿监控",
  independent:
    "独立的 IOTA Train at Home、XID / MMM、Quantus 和 fly.ai 只读监控工具，与这些项目无隶属关系。",
  privacyData:
    "免费版每个项目可关联 5 台设备，Pro 每个项目 50 台。各项目独立计数，设备总览不另设总数限制。Google 登录可跨设备同步，未登录时清单保存在当前浏览器。",
  projects: "项目",
  title: "选择你的项目",
  intro: "训练与挖矿，每个项目分别查看状态和收益记录。",
  iota: "查看上报训练贡献、网络名额和已记账 IOTA 收益。",
  xid: "查看 MMM 的 xCoin 挖矿数据：矿池 Worker、上报算力和链上记录。",
  quantus: "用公开 Wormhole 地址查看 Quantus 主网区块与 QTC 挖矿收益。",
  flyai: "用公开 ETH 收益地址查看 fly.ai 本月算力积分和钱包积分占比。",
  compute: "算力积分",
  open: "打开监控",
  training: "AI 训练",
  mining: "挖矿",
  mainnet: "主网",
  network: "网络概览",
  mine: "我的地址",
  address: "公开收益地址",
  label: "名称（选填）",
  add: "保存地址",
  remove: "移除",
  invalid: "请核对地址及校验码，使用公开的主网收益地址。",
  duplicate: "这个地址已保存。",
  limit: "每个项目免费 5 台、Pro 50 台。",
  storage: "浏览器未能保存地址清单，请检查存储权限。",
  local:
    "免费版每个项目可关联 5 台设备，Pro 每个项目 50 台。各项目独立计数，设备总览不另设总数限制。Google 登录可跨设备同步，未登录时清单保存在当前浏览器。",
  noSecrets: "只填公开地址，不要填写助记词、私钥或 inner hash。",
  empty: "添加收益地址，查看它的挖矿记录。",
  refresh: "刷新",
  refreshing: "刷新中…",
  fetched: "最近获取",
  sample: "最新来源记录",
  unavailable: "暂不可用",
  cached: "旧数据",
  sourceOld: "最新来源记录已超过 10 分钟；刷新成功不代表来源数据已更新。",
  failed: "来源刷新失败，旧数据保留原来的时间。",
  badData: "来源格式异常，已保留上次有效数据。",
  height: "区块高度",
  chainHashrate: "链上估算算力",
  poolHashrate: "观测矿池算力",
  workers: "可见活跃 Worker",
  accounts: "已索引地址",
  historicalMiners: "获得过挖矿奖励的地址",
  interval: "近期平均出块间隔",
  seconds: "秒",
  difficulty: "区块难度走势",
  blockTrend: "出块间隔",
  chartNote: "来自来源的近期区块，不是设备性能历史。",
  poolScope:
    "Worker 数据仅覆盖浏览器观测的矿池，不代表全网矿工。Worker 名称不能证明实际设备台数或型号。",
  quantusScope:
    "一个地址可能接收多台设备的奖励；链上收益无法判断设备台数、当前算力或在线状态。这里查询出块奖励，不是矿池的完整付款账本。",
  records: "最近区块",
  block: "区块",
  time: "时间",
  reward: "奖励",
  miner: "矿工",
  explorer: "查看浏览器",
  website: "官方网站",
  guide: "挖矿指南",
  sources: "数据来源与覆盖范围",
  setup: "开始使用",
  first: "安装官方矿工程序",
  second: "复制公开收益地址",
  third: "在这里添加地址",
  xidStep: "按 MMM 官方指南配置 Apple Silicon Mac；所选矿池决定哪些 Worker 记录可见。",
  quantusStep: "按官方指南配置 Quantus 主网，节点同步后再挖矿。Planck 测试网记录单独计算。",
  publicStep: "XID 使用 xpa1r 地址；Quantus 挖矿使用 qz Wormhole 地址，inner hash 留在本机。",
  monitorStep: "不同收益地址分别保存，缺失的数据会显示暂不可用。",
  worker: "Worker",
  hashrate: "矿池估算算力",
  reported: "矿工上报算力",
  shares: "有效份额",
  lastSeen: "最近活动",
  noWorkers: "本次名单没有这个地址的 Worker 记录，不能据此判断矿工离线。",
  balance: "浏览器余额",
  balanceNote: "余额不是累计挖矿收益；奖励成熟情况和可用余额请查看官方浏览器或钱包。",
  blocks: "链上归属区块",
  notFound: "暂未索引到这个地址的奖励记录，请核对地址和网络。",
  today: "今日已索引挖矿收益",
  lifetime: "累计已索引挖矿收益",
  todayNote: "香港时间今日 00:00 起；挖矿收益与钱包余额分别统计。",
  recentRewards: "最近挖矿收益",
  none: "没有返回记录。",
  poolOld: "来源将矿池数据标记为旧数据。",
  back: "全部项目",
  other: "更多项目",
  overview: "概览",
  export: "导出地址",
  download: "官方下载",
};
const tw: Copy = {
  ...zh,
  monitor: "挖礦監控",
  independent:
    "獨立的 IOTA Train at Home、XID / MMM、Quantus 和 fly.ai 唯讀監控工具，與這些專案無隸屬關係。",
  privacyData:
    "免費版每個項目可關聯 5 台設備，Pro 每個項目 50 台。各項目獨立計數，設備總覽不另設總數限制。Google 登入可跨設備同步，未登入時清單儲存在目前瀏覽器。",
  unavailable: "暫不可用",
  overview: "概覽",
  projects: "專案",
  title: "選擇你的專案",
  intro: "訓練與挖礦，每個專案分別查看狀態和收益紀錄。",
  iota: "查看回報訓練貢獻、網路名額和已記帳 IOTA 收益。",
  xid: "查看 MMM 的 xCoin 挖礦資料：礦池 Worker、回報算力和鏈上紀錄。",
  quantus: "用公開 Wormhole 地址查看 Quantus 主網區塊與 QTC 挖礦收益。",
  flyai: "用公開 ETH 收益地址查看 fly.ai 本月算力積分和錢包積分佔比。",
  compute: "算力積分",
  open: "開啟監控",
  training: "AI 訓練",
  mining: "挖礦",
  network: "網路概覽",
  mine: "我的地址",
  address: "公開收益地址",
  label: "名稱（選填）",
  add: "儲存地址",
  invalid: "請核對地址及校驗碼，使用公開的主網收益地址。",
  duplicate: "這個地址已儲存。",
  limit: "每個專案每個項目免費 5 台、Pro 50 台。",
  storage: "瀏覽器未能儲存地址清單，請檢查儲存權限。",
  local:
    "免費版每個項目可關聯 5 台設備，Pro 每個項目 50 台。各項目獨立計數，設備總覽不另設總數限制。Google 登入可跨設備同步，未登入時清單儲存在目前瀏覽器。",
  noSecrets: "只填公開地址，不要填寫助記詞、私鑰或 inner hash。",
  empty: "新增收益地址，查看它的挖礦紀錄。",
  refreshing: "重新整理中…",
  refresh: "重新整理",
  fetched: "最近取得",
  sample: "最新來源紀錄",
  cached: "舊資料",
  sourceOld: "最新來源紀錄已超過 10 分鐘；重新整理成功不代表來源資料已更新。",
  failed: "來源更新失敗，舊資料保留原來的時間。",
  badData: "來源格式異常，已保留上次有效資料。",
  height: "區塊高度",
  chainHashrate: "鏈上估算算力",
  poolHashrate: "觀測礦池算力",
  workers: "可見活躍 Worker",
  accounts: "已索引地址",
  historicalMiners: "獲得過挖礦獎勵的地址",
  interval: "近期平均出塊間隔",
  difficulty: "區塊難度走勢",
  blockTrend: "出塊間隔",
  chartNote: "來自來源的近期區塊，不是設備效能歷史。",
  poolScope:
    "Worker 資料僅涵蓋瀏覽器觀測的礦池，不代表全網礦工。Worker 名稱不能證明實際設備台數或型號。",
  quantusScope:
    "一個地址可能接收多台設備的獎勵；鏈上收益無法判斷設備台數、目前算力或上線狀態。這裡查詢出塊獎勵，不是礦池完整付款帳本。",
  records: "最近區塊",
  block: "區塊",
  time: "時間",
  reward: "獎勵",
  miner: "礦工",
  explorer: "查看瀏覽器",
  website: "官方網站",
  guide: "挖礦指南",
  sources: "資料來源與涵蓋範圍",
  setup: "開始使用",
  first: "安裝官方礦工程式",
  second: "複製公開收益地址",
  third: "在這裡新增地址",
  xidStep: "按 MMM 官方指南設定 Apple Silicon Mac；所選礦池決定哪些 Worker 紀錄可見。",
  quantusStep: "按官方指南設定 Quantus 主網，節點同步後再挖礦。Planck 測試網紀錄單獨計算。",
  publicStep: "XID 使用 xpa1r 地址；Quantus 挖礦使用 qz Wormhole 地址，inner hash 留在本機。",
  monitorStep: "不同收益地址分別儲存，缺失的資料會顯示暫不可用。",
  hashrate: "礦池估算算力",
  reported: "礦工回報算力",
  shares: "有效份額",
  lastSeen: "最近活動",
  noWorkers: "本次名單沒有這個地址的 Worker 紀錄，不能據此判斷礦工離線。",
  balance: "瀏覽器餘額",
  balanceNote: "餘額不是累計挖礦收益；獎勵成熟情況和可用餘額請查看官方瀏覽器或錢包。",
  blocks: "鏈上歸屬區塊",
  notFound: "暫未索引到這個地址的獎勵紀錄，請核對地址和網路。",
  today: "今日已索引挖礦收益",
  lifetime: "累計已索引挖礦收益",
  todayNote: "香港時間今日 00:00 起；挖礦收益與錢包餘額分別統計。",
  recentRewards: "最近挖礦收益",
  none: "沒有回傳紀錄。",
  poolOld: "來源將礦池資料標記為舊資料。",
  back: "全部專案",
  other: "更多專案",
  export: "匯出地址",
  download: "官方下載",
};
const ko: Copy = {
  monitor: "채굴 모니터",
  independent:
    "IOTA Train at Home, XID / MMM, Quantus, fly.ai의 독립적인 읽기 전용 모니터입니다. 각 프로젝트의 공식 서비스가 아닙니다.",
  privacyData:
    "무료는 프로젝트별 기기 5대, Pro는 프로젝트별 50대를 지원합니다. 프로젝트 한도는 독립적이며 기기 개요에 별도의 총수 제한은 없습니다. Google 로그인으로 기기 간 목록을 동기화할 수 있습니다. 로그인하지 않으면 목록은 이 브라우저에 저장됩니다.",
  projects: "프로젝트",
  title: "프로젝트 선택",
  intro: "학습과 채굴 상태 및 보상 기록을 프로젝트별로 확인하세요.",
  iota: "보고된 학습 기여도, 네트워크 슬롯, 기록된 IOTA 보상을 확인합니다.",
  xid: "MMM의 xCoin 채굴 데이터: 풀 워커, 보고된 해시레이트, 온체인 기록을 확인합니다.",
  quantus: "공개 Wormhole 주소로 Quantus 메인넷 블록과 QTC 채굴 보상을 확인합니다.",
  flyai: "공개 ETH 보상 주소로 fly.ai의 월간 컴퓨팅 포인트와 지갑 비중을 확인합니다.",
  compute: "컴퓨팅 포인트",
  open: "모니터 열기",
  training: "AI 학습",
  mining: "채굴",
  mainnet: "메인넷",
  network: "네트워크 현황",
  mine: "내 주소",
  address: "공개 보상 주소",
  label: "이름 (선택)",
  add: "주소 저장",
  remove: "삭제",
  invalid: "주소와 체크섬을 확인하세요. 공개 메인넷 보상 주소를 사용하세요.",
  duplicate: "이미 저장된 주소입니다.",
  limit:
    "무료는 프로젝트별 기기 5대, Pro는 프로젝트별 50대를 지원합니다. 프로젝트 한도는 독립적이며 기기 개요에 별도의 총수 제한은 없습니다. Google 로그인으로 기기 간 목록을 동기화할 수 있습니다. 로그인하지 않으면 목록은 이 브라우저에 저장됩니다.",
  storage: "브라우저가 주소 목록을 저장하지 못했습니다. 저장 권한을 확인하세요.",
  local: "프로젝트별로 이 브라우저에 저장됩니다. 계정과 동기화되지 않습니다.",
  noSecrets: "공개 주소만 입력하세요. 시드 문구, 개인 키, inner hash는 입력하지 마세요.",
  empty: "보상 주소를 추가하여 채굴 기록을 확인하세요.",
  refresh: "새로고침",
  refreshing: "새로고침 중…",
  fetched: "최근 조회",
  sample: "최신 원본 기록",
  unavailable: "확인 불가",
  cached: "이전 데이터",
  sourceOld:
    "최신 원본 기록이 10분 이상 지났습니다. 새로고침 성공이 최신 데이터를 의미하지 않습니다.",
  failed: "원본 데이터를 갱신하지 못했습니다. 이전 데이터의 시각을 유지합니다.",
  badData: "원본 형식이 올바르지 않습니다. 마지막 유효 데이터를 유지합니다.",
  height: "블록 높이",
  chainHashrate: "온체인 추정 해시레이트",
  poolHashrate: "관측 풀 해시레이트",
  workers: "확인 가능한 활성 워커",
  accounts: "색인된 주소",
  historicalMiners: "채굴 보상을 받은 주소",
  interval: "최근 평균 블록 간격",
  seconds: "초",
  difficulty: "블록별 난이도",
  blockTrend: "블록 간격",
  chartNote: "원본의 최근 블록 데이터이며 장치 성능 이력이 아닙니다.",
  poolScope:
    "워커 데이터는 탐색기가 관측한 풀만 포함합니다. 워커 이름으로 실제 장치 수나 모델을 알 수 없습니다.",
  quantusScope:
    "한 주소가 여러 장치의 보상을 받을 수 있습니다. 온체인 보상으로 장치 수, 현재 해시레이트 또는 온라인 상태를 판단할 수 없습니다. 이 인덱스는 블록 보상을 다루며 풀의 전체 지급 장부가 아닙니다.",
  records: "최근 블록",
  block: "블록",
  time: "시각",
  reward: "보상",
  miner: "채굴자",
  explorer: "탐색기 열기",
  website: "공식 웹사이트",
  guide: "채굴 가이드",
  sources: "데이터 출처와 범위",
  setup: "시작하기",
  first: "공식 채굴 프로그램 설치",
  second: "공개 보상 주소 복사",
  third: "여기에 주소 추가",
  xidStep:
    "Apple Silicon용 MMM 공식 가이드에 따라 설정하세요. 선택한 풀에 따라 확인 가능한 워커 기록이 달라집니다.",
  quantusStep:
    "Quantus 메인넷 공식 가이드를 사용하세요. 노드 동기화 후 채굴을 시작하세요. Planck 테스트넷 기록은 별도입니다.",
  publicStep:
    "XID는 xpa1r 주소, Quantus 채굴은 qz Wormhole 주소를 사용합니다. inner hash는 장치에 보관하세요.",
  monitorStep: "각 보상 주소를 따로 저장하세요. 누락된 데이터는 확인 불가로 표시됩니다.",
  worker: "워커",
  hashrate: "풀 추정 해시레이트",
  reported: "채굴자 보고 해시레이트",
  shares: "유효 셰어",
  lastSeen: "최근 활동",
  noWorkers: "조회한 목록에 이 주소의 워커 기록이 없습니다. 오프라인이라는 의미는 아닙니다.",
  balance: "탐색기 잔액",
  balanceNote:
    "잔액은 누적 채굴 수입이 아닙니다. 보상 성숙 여부와 사용 가능 잔액은 공식 탐색기나 지갑에서 확인하세요.",
  blocks: "온체인 귀속 블록",
  notFound: "이 주소의 보상 기록이 아직 색인되지 않았습니다. 주소와 네트워크를 확인하세요.",
  today: "오늘 색인된 채굴 보상",
  lifetime: "누적 색인된 채굴 보상",
  todayNote: "홍콩 시간 00:00부터 집계합니다. 채굴 보상과 지갑 잔액은 별도입니다.",
  recentRewards: "최근 채굴 보상",
  none: "반환된 기록이 없습니다.",
  poolOld: "원본에서 풀 데이터가 오래된 것으로 표시되었습니다.",
  back: "모든 프로젝트",
  other: "다른 프로젝트",
  overview: "개요",
  export: "주소 내보내기",
  download: "공식 다운로드",
};
const ja: Copy = {
  monitor: "マイニングモニター",
  independent:
    "IOTA Train at Home、XID / MMM、Quantus、fly.aiの独立した読み取り専用モニターです。各プロジェクトの公式サービスではありません。",
  privacyData:
    "無料版は各プロジェクト5台、Proは各50台に対応します。各プロジェクトの枠は独立し、デバイス一覧に別途の総数制限はありません。Googleログインでデバイス間の一覧を同期でき、ログインしない場合はこのブラウザーに保存されます。",
  projects: "プロジェクト",
  title: "プロジェクトを選択",
  intro: "学習とマイニングの状態・報酬記録をプロジェクトごとに確認できます。",
  iota: "報告された学習貢献、ネットワーク枠、記帳済み IOTA 報酬を確認します。",
  xid: "MMM の xCoin マイニングを監視：プールのワーカー、報告されたハッシュレート、オンチェーン記録。",
  quantus:
    "公開 Wormhole アドレスで Quantus メインネットのブロックと QTC マイニング報酬を確認します。",
  flyai: "公開 ETH 報酬アドレスで fly.ai の月間計算ポイントとウォレットの割合を確認します。",
  compute: "計算ポイント",
  open: "モニターを開く",
  training: "AI 学習",
  mining: "マイニング",
  mainnet: "メインネット",
  network: "ネットワーク概要",
  mine: "マイアドレス",
  address: "公開報酬アドレス",
  label: "名前（任意）",
  add: "アドレスを保存",
  remove: "削除",
  invalid: "アドレスとチェックサムを確認してください。公開メインネット報酬アドレスを使用します。",
  duplicate: "このアドレスは保存済みです。",
  limit:
    "無料版は各プロジェクト5台、Proは各50台に対応します。各プロジェクトの枠は独立し、デバイス一覧に別途の総数制限はありません。Googleログインでデバイス間の一覧を同期でき、ログインしない場合はこのブラウザーに保存されます。",
  storage: "ブラウザがアドレス一覧を保存できませんでした。保存権限を確認してください。",
  local: "プロジェクトごとにこのブラウザに保存されます。アカウントとは同期されません。",
  noSecrets: "公開アドレスのみ。シードフレーズ、秘密鍵、inner hash は入力しないでください。",
  empty: "報酬アドレスを追加してマイニング記録を確認します。",
  refresh: "更新",
  refreshing: "更新中…",
  fetched: "最終取得",
  sample: "最新のソース記録",
  unavailable: "取得不可",
  cached: "過去のデータ",
  sourceOld:
    "最新のソース記録から 10 分以上経過しています。更新成功はデータが最新であることを意味しません。",
  failed: "ソースを更新できませんでした。以前のデータの時刻を保持します。",
  badData: "ソースの形式が不正です。前回の有効なデータを保持します。",
  height: "ブロック高",
  chainHashrate: "オンチェーン推定ハッシュレート",
  poolHashrate: "観測プールのハッシュレート",
  workers: "確認できる稼働ワーカー",
  accounts: "索引済みアドレス",
  historicalMiners: "採掘報酬を受け取ったアドレス",
  interval: "直近の平均ブロック間隔",
  seconds: "秒",
  difficulty: "ブロックごとの難易度",
  blockTrend: "ブロック間隔",
  chartNote: "ソースの直近ブロックです。デバイス性能の履歴ではありません。",
  poolScope:
    "ワーカーデータはエクスプローラーが観測したプールのみです。名前から実際のデバイス数や機種は判断できません。",
  quantusScope:
    "一つのアドレスで複数のデバイスの報酬を受け取れます。オンチェーン報酬では台数、現在のハッシュレート、接続状態は判断できません。 この索引はブロック報酬を扱い、プールの全支払台帳ではありません。",
  records: "最近のブロック",
  block: "ブロック",
  time: "時刻",
  reward: "報酬",
  miner: "マイナー",
  explorer: "エクスプローラーを開く",
  website: "公式サイト",
  guide: "マイニングガイド",
  sources: "データソースと範囲",
  setup: "使い始める",
  first: "公式マイナーをインストール",
  second: "公開報酬アドレスをコピー",
  third: "ここにアドレスを追加",
  xidStep:
    "Apple Silicon 向け MMM 公式ガイドに従って設定します。選択したプールにより確認できるワーカー記録が異なります。",
  quantusStep:
    "Quantus メインネット公式ガイドを使用します。ノード同期後に採掘してください。Planck テストネット記録は別です。",
  publicStep:
    "XID は xpa1r、Quantus 採掘は qz Wormhole アドレスです。inner hash はデバイスに保管します。",
  monitorStep: "報酬アドレスを個別に保存します。欠落したデータは取得不可と表示します。",
  worker: "ワーカー",
  hashrate: "プール推定ハッシュレート",
  reported: "マイナー報告ハッシュレート",
  shares: "有効シェア",
  lastSeen: "最近の活動",
  noWorkers: "取得した一覧にこのアドレスのワーカー記録はありません。オフラインとは限りません。",
  balance: "エクスプローラー残高",
  balanceNote:
    "残高は累計採掘収入ではありません。報酬の成熟状況と利用可能残高は公式エクスプローラーまたはウォレットで確認してください。",
  blocks: "オンチェーン帰属ブロック",
  notFound:
    "このアドレスの報酬記録はまだ索引されていません。アドレスとネットワークを確認してください。",
  today: "本日索引済みの採掘報酬",
  lifetime: "累計索引済みの採掘報酬",
  todayNote: "香港時間 00:00 から集計。採掘報酬とウォレット残高は別です。",
  recentRewards: "最近の採掘報酬",
  none: "記録が返されませんでした。",
  poolOld: "ソースがプールデータを古いと判定しています。",
  back: "すべてのプロジェクト",
  other: "他のプロジェクト",
  overview: "概要",
  export: "アドレスをエクスポート",
  download: "公式ダウンロード",
};
export const projectsCopy: Record<SiteLocale, Copy> = { en, zh, "zh-TW": tw, ko, ja };
