/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AppRouteImport } from './routes/app'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAccountRouteImport } from './routes/$locale.account'
import { Route as LocaleAppRouteImport } from './routes/$locale.app'
import { Route as LocaleFaqRouteImport } from './routes/$locale.faq'
import { Route as LocaleGuideRouteImport } from './routes/$locale.guide'
import { Route as LocalePrivacyRouteImport } from './routes/$locale.privacy'
import { Route as LocaleLearnChar123SlugChar125RouteImport } from './routes/$locale.learn.{-$slug}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAccountRoute = LocaleAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppRoute = LocaleAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGuideRoute = LocaleGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLearnChar123SlugChar125Route =
  LocaleLearnChar123SlugChar125RouteImport.update({
    id: '/learn/{-$slug}',
    path: '/learn/{-$slug}',
    getParentRoute: () => LocaleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/guide': typeof LocaleGuideRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/learn/{-$slug}': typeof LocaleLearnChar123SlugChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/guide': typeof LocaleGuideRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/learn/{-$slug}': typeof LocaleLearnChar123SlugChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/guide': typeof LocaleGuideRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/learn/{-$slug}': typeof LocaleLearnChar123SlugChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/app'
    | '/$locale/account'
    | '/$locale/app'
    | '/$locale/faq'
    | '/$locale/guide'
    | '/$locale/privacy'
    | '/$locale/'
    | '/$locale/learn/{-$slug}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/$locale/account'
    | '/$locale/app'
    | '/$locale/faq'
    | '/$locale/guide'
    | '/$locale/privacy'
    | '/$locale'
    | '/$locale/learn/{-$slug}'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/app'
    | '/$locale/account'
    | '/$locale/app'
    | '/$locale/faq'
    | '/$locale/guide'
    | '/$locale/privacy'
    | '/$locale/'
    | '/$locale/learn/{-$slug}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AppRoute: typeof AppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account': {
      id: '/$locale/account'
      path: '/account'
      fullPath: '/$locale/account'
      preLoaderRoute: typeof LocaleAccountRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app': {
      id: '/$locale/app'
      path: '/app'
      fullPath: '/$locale/app'
      preLoaderRoute: typeof LocaleAppRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/guide': {
      id: '/$locale/guide'
      path: '/guide'
      fullPath: '/$locale/guide'
      preLoaderRoute: typeof LocaleGuideRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/learn/{-$slug}': {
      id: '/$locale/learn/{-$slug}'
      path: '/learn/{-$slug}'
      fullPath: '/$locale/learn/{-$slug}'
      preLoaderRoute: typeof LocaleLearnChar123SlugChar125RouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAccountRoute: typeof LocaleAccountRoute
  LocaleAppRoute: typeof LocaleAppRoute
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocaleGuideRoute: typeof LocaleGuideRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleLearnChar123SlugChar125Route: typeof LocaleLearnChar123SlugChar125Route
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAccountRoute: LocaleAccountRoute,
  LocaleAppRoute: LocaleAppRoute,
  LocaleFaqRoute: LocaleFaqRoute,
  LocaleGuideRoute: LocaleGuideRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleLearnChar123SlugChar125Route: LocaleLearnChar123SlugChar125Route,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AppRoute: AppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
