/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AppRouteImport } from './routes/app'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAccountRouteImport } from './routes/$locale.account'
import { Route as LocaleAppRouteImport } from './routes/$locale.app'
import { Route as LocaleDevicesRouteImport } from './routes/$locale.devices'
import { Route as LocaleDownloadsRouteImport } from './routes/$locale.downloads'
import { Route as LocaleFaqRouteImport } from './routes/$locale.faq'
import { Route as LocaleGuideRouteImport } from './routes/$locale.guide'
import { Route as LocaleNetworkRouteImport } from './routes/$locale.network'
import { Route as LocalePrivacyRouteImport } from './routes/$locale.privacy'
import { Route as LocaleReviewRouteImport } from './routes/$locale.review'
import { Route as LocaleBlogChar123SlugChar125RouteImport } from './routes/$locale.blog.{-$slug}'
import { Route as LocaleLearnChar123SlugChar125RouteImport } from './routes/$locale.learn.{-$slug}'
import { Route as LocaleProjectsChar123ProjectChar125RouteImport } from './routes/$locale.projects.{-$project}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAccountRoute = LocaleAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppRoute = LocaleAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDevicesRoute = LocaleDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDownloadsRoute = LocaleDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGuideRoute = LocaleGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleNetworkRoute = LocaleNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReviewRoute = LocaleReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogChar123SlugChar125Route =
  LocaleBlogChar123SlugChar125RouteImport.update({
    id: '/blog/{-$slug}',
    path: '/blog/{-$slug}',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleLearnChar123SlugChar125Route =
  LocaleLearnChar123SlugChar125RouteImport.update({
    id: '/learn/{-$slug}',
    path: '/learn/{-$slug}',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleProjectsChar123ProjectChar125Route =
  LocaleProjectsChar123ProjectChar125RouteImport.update({
    id: '/projects/{-$project}',
    path: '/projects/{-$project}',
    getParentRoute: () => LocaleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/devices': typeof LocaleDevicesRoute
  '/$locale/downloads': typeof LocaleDownloadsRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/guide': typeof LocaleGuideRoute
  '/$locale/network': typeof LocaleNetworkRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/review': typeof LocaleReviewRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/{-$slug}': typeof LocaleBlogChar123SlugChar125Route
  '/$locale/learn/{-$slug}': typeof LocaleLearnChar123SlugChar125Route
  '/$locale/projects/{-$project}': typeof LocaleProjectsChar123ProjectChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/devices': typeof LocaleDevicesRoute
  '/$locale/downloads': typeof LocaleDownloadsRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/guide': typeof LocaleGuideRoute
  '/$locale/network': typeof LocaleNetworkRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/review': typeof LocaleReviewRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/{-$slug}': typeof LocaleBlogChar123SlugChar125Route
  '/$locale/learn/{-$slug}': typeof LocaleLearnChar123SlugChar125Route
  '/$locale/projects/{-$project}': typeof LocaleProjectsChar123ProjectChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/devices': typeof LocaleDevicesRoute
  '/$locale/downloads': typeof LocaleDownloadsRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/guide': typeof LocaleGuideRoute
  '/$locale/network': typeof LocaleNetworkRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/review': typeof LocaleReviewRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/{-$slug}': typeof LocaleBlogChar123SlugChar125Route
  '/$locale/learn/{-$slug}': typeof LocaleLearnChar123SlugChar125Route
  '/$locale/projects/{-$project}': typeof LocaleProjectsChar123ProjectChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/app'
    | '/$locale/account'
    | '/$locale/app'
    | '/$locale/devices'
    | '/$locale/downloads'
    | '/$locale/faq'
    | '/$locale/guide'
    | '/$locale/network'
    | '/$locale/privacy'
    | '/$locale/review'
    | '/$locale/'
    | '/$locale/blog/{-$slug}'
    | '/$locale/learn/{-$slug}'
    | '/$locale/projects/{-$project}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/$locale/account'
    | '/$locale/app'
    | '/$locale/devices'
    | '/$locale/downloads'
    | '/$locale/faq'
    | '/$locale/guide'
    | '/$locale/network'
    | '/$locale/privacy'
    | '/$locale/review'
    | '/$locale'
    | '/$locale/blog/{-$slug}'
    | '/$locale/learn/{-$slug}'
    | '/$locale/projects/{-$project}'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/app'
    | '/$locale/account'
    | '/$locale/app'
    | '/$locale/devices'
    | '/$locale/downloads'
    | '/$locale/faq'
    | '/$locale/guide'
    | '/$locale/network'
    | '/$locale/privacy'
    | '/$locale/review'
    | '/$locale/'
    | '/$locale/blog/{-$slug}'
    | '/$locale/learn/{-$slug}'
    | '/$locale/projects/{-$project}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AppRoute: typeof AppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account': {
      id: '/$locale/account'
      path: '/account'
      fullPath: '/$locale/account'
      preLoaderRoute: typeof LocaleAccountRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app': {
      id: '/$locale/app'
      path: '/app'
      fullPath: '/$locale/app'
      preLoaderRoute: typeof LocaleAppRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/devices': {
      id: '/$locale/devices'
      path: '/devices'
      fullPath: '/$locale/devices'
      preLoaderRoute: typeof LocaleDevicesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/downloads': {
      id: '/$locale/downloads'
      path: '/downloads'
      fullPath: '/$locale/downloads'
      preLoaderRoute: typeof LocaleDownloadsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/guide': {
      id: '/$locale/guide'
      path: '/guide'
      fullPath: '/$locale/guide'
      preLoaderRoute: typeof LocaleGuideRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/network': {
      id: '/$locale/network'
      path: '/network'
      fullPath: '/$locale/network'
      preLoaderRoute: typeof LocaleNetworkRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/review': {
      id: '/$locale/review'
      path: '/review'
      fullPath: '/$locale/review'
      preLoaderRoute: typeof LocaleReviewRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/{-$slug}': {
      id: '/$locale/blog/{-$slug}'
      path: '/blog/{-$slug}'
      fullPath: '/$locale/blog/{-$slug}'
      preLoaderRoute: typeof LocaleBlogChar123SlugChar125RouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/learn/{-$slug}': {
      id: '/$locale/learn/{-$slug}'
      path: '/learn/{-$slug}'
      fullPath: '/$locale/learn/{-$slug}'
      preLoaderRoute: typeof LocaleLearnChar123SlugChar125RouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/projects/{-$project}': {
      id: '/$locale/projects/{-$project}'
      path: '/projects/{-$project}'
      fullPath: '/$locale/projects/{-$project}'
      preLoaderRoute: typeof LocaleProjectsChar123ProjectChar125RouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAccountRoute: typeof LocaleAccountRoute
  LocaleAppRoute: typeof LocaleAppRoute
  LocaleDevicesRoute: typeof LocaleDevicesRoute
  LocaleDownloadsRoute: typeof LocaleDownloadsRoute
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocaleGuideRoute: typeof LocaleGuideRoute
  LocaleNetworkRoute: typeof LocaleNetworkRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleReviewRoute: typeof LocaleReviewRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogChar123SlugChar125Route: typeof LocaleBlogChar123SlugChar125Route
  LocaleLearnChar123SlugChar125Route: typeof LocaleLearnChar123SlugChar125Route
  LocaleProjectsChar123ProjectChar125Route: typeof LocaleProjectsChar123ProjectChar125Route
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAccountRoute: LocaleAccountRoute,
  LocaleAppRoute: LocaleAppRoute,
  LocaleDevicesRoute: LocaleDevicesRoute,
  LocaleDownloadsRoute: LocaleDownloadsRoute,
  LocaleFaqRoute: LocaleFaqRoute,
  LocaleGuideRoute: LocaleGuideRoute,
  LocaleNetworkRoute: LocaleNetworkRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleReviewRoute: LocaleReviewRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogChar123SlugChar125Route: LocaleBlogChar123SlugChar125Route,
  LocaleLearnChar123SlugChar125Route: LocaleLearnChar123SlugChar125Route,
  LocaleProjectsChar123ProjectChar125Route:
    LocaleProjectsChar123ProjectChar125Route,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AppRoute: AppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
